/**
 * UI strings for the staff screens — the booth kiosk, its statistics page, the bar they share,
 * and the account page.
 *
 * No i18n library. At this size a typed dictionary buys something react-i18next cannot: `th` is
 * declared `Record<keyof typeof en, string>`, so a missing or misspelt key is a *build* error
 * rather than an English word surfacing in a Thai interface during the festival.
 *
 * `{name}` placeholders are filled by `t('key', { name })`.
 *
 * Scope note: spec §1.4 chose an English interface deliberately, because the visitors this event
 * exists to bring together do not share Thai. Thai is therefore an addition for Thai-speaking
 * staff and visitors, not a replacement — and the admin panel (~230 further strings, mostly
 * reporting vocabulary) stays English.
 */
import { adminEn, adminTh } from './strings.admin'

const staffEn = {
  'lang.label': 'Language',

  // OrganizerBar
  'nav.pages': 'Booth pages',
  'nav.booth': 'Booth screen',
  'nav.stats': 'Stats',
  'nav.survey': 'Survey',
  'nav.desk': 'Prize desk',
  'nav.admin': 'Admin',
  'nav.account': 'Account',
  'nav.profile': 'Profile',
  'nav.myPassport': 'My passport',
  'nav.accountSettings': 'Account settings',
  'nav.menu': 'Menu',
  'nav.signOut': 'Sign out',

  // Booth kiosk
  'booth.worth': '{location} · This badge is worth {points} points',
  'booth.manualCode': 'Manual code',
  'booth.rotatesIn': 'Rotates in',
  'booth.seconds': 's',
  'booth.visitorsHere': 'Visitors here',
  'booth.eventTotal': 'Event total',
  'booth.rankOf': 'Rank of {count} booths',
  'booth.starting': 'Starting booth screen…',
  'booth.failed': 'This screen could not start',
  'booth.retry': 'Try again',
  'booth.fsUnavailable': 'Full screen is not available in this browser — press F11.',
  'booth.fsBlocked': 'Full screen was blocked — press F11 (⌃⌘F on a Mac).',
  // iPhone Safari has no Fullscreen API at all, so the advice is Add to Home Screen instead.
  'booth.fsIos': 'iPhone and iPad cannot go full screen from inside Safari. Tap Share, then “Add to Home Screen”, and open the booth screen from that icon — it runs without the address bar.',
  'booth.fullScreen': 'Full screen',
  'booth.exitFullScreen': 'Exit full screen',
  'booth.printCard': 'Print card',
  'booth.showCode': 'Show code to visitor',
  'booth.closeCode': 'Back to booth screen',
  'booth.switchedOff': 'This booth was switched off by the admin — visitor scans are refused until it is switched back on.',
  'booth.notToday': "Not scheduled today on the visitors' stamp map — codes still work if someone scans.",

  // status
  'status.live': 'Live',
  'status.reconnecting': 'Reconnecting',
  'status.offlineCodes': 'Offline — codes still valid',
  'status.reconnectingCodes': 'Reconnecting — codes still valid',

  // Stats
  'stats.worth': '{location} · worth {points} points',
  'stats.visitorsStamped': 'Visitors stamped',
  'stats.lastAt': 'Last at {time}',
  'stats.noneYet': 'None yet',
  'stats.perHour': 'Visitors per hour · Day {day}',
  'stats.day': 'Day',
  'stats.dayN': 'Day {n}',
  'stats.whoVisited': 'Who visited',
  'stats.byDay': 'By day',
  'stats.loading': 'Loading your booth…',
  'stats.noBooth': 'No booth is linked to this account yet — ask the admin to assign one.',
  'stats.boothGone': 'This booth no longer exists. Ask the admin which booth is yours.',

  // Account
  'account.title': 'Your account',
  'account.signedIn': 'Signed in',
  'account.back': 'Back',

  'acct.email.title': 'Email address',
  'acct.email.note': 'Signing in and every notice go to this address.',
  'acct.email.confirmed': 'Confirmed.',
  'acct.email.unconfirmed': 'Not confirmed yet.',
  'acct.email.ok': 'Confirmed',
  'acct.email.pending': 'Not confirmed',
  'acct.email.change': 'Change my email address',
  'acct.email.new': 'New email',
  'acct.email.sendAgain': 'Send the confirmation link again',
  'acct.email.send': 'Send the confirmation',
  'acct.email.sending': 'Sending…',
  'acct.email.sent': 'Confirmation link sent. Tap it, then reopen this page.',

  'acct.pw.title': 'Password',
  'acct.pw.noteGoogle': 'You sign in with Google. Add a password if you also want to sign in without it.',
  'acct.pw.noteHas': 'Used together with your email to sign in.',
  'acct.pw.add': 'Add a password',
  'acct.pw.change': 'Change my password',
  'acct.pw.current': 'Current password',
  'acct.pw.new': 'New password',
  'acct.pw.confirm': 'Confirm new password',
  'acct.pw.mismatch': 'The two passwords do not match.',
  'acct.pw.forgot': 'Forgotten it? Send a reset link instead',
  'acct.pw.changed': 'Password changed.',
  'acct.pw.added': 'Password added. You can now sign in with your email as well as with Google.',

  'acct.methods.title': 'Sign-in methods',
  'acct.methods.google': 'Google',
  'acct.methods.password': 'Email and password',
  'acct.methods.on': 'Connected',
  'acct.methods.off': 'Not connected',
  'acct.pw.none': 'Not set',

  'acct.leaving.title': 'Leaving',
  'acct.leaving.note': 'Signing out keeps your passport safe on the server. Sign back in on any phone to open it again.',
  'acct.leaving.signOut': 'Sign out',
  'acct.erase.ask': 'Ask for my data to be deleted',
  'acct.erase.request': 'Request erasure',
  'acct.erase.requested': 'Erasure requested{date}. The organisers will delete your account; you can keep using your passport until then.',
  'acct.erase.on': ' on {date}',


  // ---------- visitor app (pages/visitor/*) ----------
  'v.lang': 'ภาษา / Language',

  // chrome
  'v.tab.cover': 'Cover',
  'v.tab.stamps': 'Stamps',
  'v.tab.prize': 'Prize',
  'v.tab.profile': 'Profile',
  'v.offline': 'Offline — your stamps are saved',
  'v.offline.note': 'This page will catch up on its own. You will need a connection to collect a new stamp.',
  'v.back.passport': 'Passport',
  'v.back.prize': 'Prize',
  'v.close': 'Close',
  'v.loading': 'Opening your passport…',

  // landing
  'v.landing.university': 'Mae Fah Luang University',
  'v.landing.badge': 'Digital passport',
  'v.landing.pitch': 'Collect a stamp at every booth with your own phone, earn points, and trade them for a prize.',
  'v.landing.start': 'Start your passport',
  'v.landing.have': 'I already have a passport',

  // cover
  'v.cover.passport': 'Passport',
  'v.cover.pointsStamps': 'points · {have} of {total} stamps',
  'v.cover.toGo': 'to go',
  'v.cover.topTier': 'top tier',
  'v.cover.nextUp': 'Next up',
  'v.cover.allTiers': 'You have reached every tier. Show your Prize page at the desk.',
  'v.cover.goHere': 'Go here next',
  'v.cover.points': 'points',
  'v.cover.allStamped': 'Every booth stamped. Take your passport to the prize desk.',
  'v.cover.nothingToday': 'Nothing left to collect today — check back tomorrow for the booths that rotate.',

  // stamps
  'v.stamps.title': 'Stamps',
  'v.stamps.ofTotal': '{have} of {total}',
  'v.stamps.progress': '{have} of {total} booths stamped',
  'v.stamps.yours': 'Your stamps',
  'v.stamps.none': 'No stamps yet. Tap Scan at your first booth.',
  'v.stamps.stamped': 'Stamped',
  'v.stamps.earning': 'Loading earned points…',
  'v.stamps.plusPts': '+{n} pts',
  'v.stamps.left': 'Still to collect',
  'v.stamps.onFloor': '{n} points still on the floor',
  'v.stamps.rewardsNote': 'Rewards may change. Points are set when your stamp is earned. Times shown are Bangkok time.',
  'v.stamps.onlyOn': '{days} only',
  'v.stamps.pts': '{n} pts',
  'v.stamps.pointsEarned': 'points earned',
  'v.stamps.pointsWorth': 'points',
  'v.stamps.present': 'Present: {days}',
  'v.stamps.viewFull': 'View full screen',
  'v.stamps.day': 'Day {n}',
  'v.stamps.visa': '{booth} visa',

  // scan
  'v.scan.title': 'Scan a booth',
  'v.scan.checkin': 'Booth check-in',
  'v.scan.checking': 'Checking…',
  'v.scan.stamping': 'Stamping…',
  'v.scan.checkingStamp': 'Checking your stamp…',
  'v.scan.offline': 'No connection. A stamp is saved on the server, so this needs a moment of signal — the booth code stays valid while you wait.',
  'v.scan.manualLabel': 'Or type the 6-character code under the QR',
  'v.scan.stamp': 'Stamp',
  'v.scan.aria': 'Scan a booth',

  // scan result
  'v.res.collected': 'Stamp collected',
  'v.res.plusPoints': '+{n} points',
  'v.res.summary': '{booth} · {points} points total · {stamps} stamps',
  'v.res.unlocked': 'You just unlocked a prize tier. Check the Prize page.',
  'v.res.scanAnother': 'Scan another',
  'v.res.myStamps': 'My stamps',
  'v.res.already': 'Already stamped here',
  'v.res.alreadyNote': '{booth} is in your passport. Try a booth you have not visited.',
  'v.res.whatsLeft': 'See what\u2019s left',
  'v.res.expired': 'That code has expired — the booth screen changes every 20 seconds. Scan it again.',
  'v.res.invalid': 'Invalid code. Point your camera at the booth screen, or type the 6 characters shown under the QR.',
  'v.res.tooFast': 'Too fast — give it a few seconds and try again.',
  'v.res.notRegistered': 'Create your passport first, then scan.',
  'v.res.createPassport': 'Create my passport',
  'v.res.tryAgain': 'Try again',

  // rating
  'v.rate.title': 'How was this booth?',
  'v.rate.lead': 'Your points are already saved — this just tells the organizers how it went.',
  'v.rate.aria': 'Rate this booth from 1 to 5 stars',
  'v.rate.star': '{n} star',
  'v.rate.stars': '{n} stars',
  'v.rate.comment': 'Anything to add? (optional)',
  'v.rate.placeholder': 'What made it good, or what would make it better',
  'v.rate.pick': 'Pick a star to continue',
  'v.rate.send': 'Send',
  'v.rate.sending': 'Sending…',
  'v.rate.thanks': 'Thank you',
  'v.rate.failed': 'We could not save your rating just now — carry on, it is not holding anything up.',
  'v.rate.rated': 'You rated {n} out of 5',

  // prize
  // Booth staff who arrive without an invitation (pages/visitor/BoothAccess.tsx). A request, never
  // a grant — the copy has to be honest that an admin still decides, or someone will stand at the
  // booth waiting for a screen that is not coming.
  'v.staff.title': 'Run a booth',
  'v.staff.lead': 'If you are running a booth and were not sent an invitation, ask here. An organiser will check and switch your account over.',
  'v.staff.signInFirst': 'Sign in first, with any account — then tell us which booth is yours.',
  'v.staff.signIn': 'Sign in',
  'v.staff.signUp': 'Create an account',
  'v.staff.pickBooth': 'Your booth',
  'v.staff.pickPlaceholder': '— choose your booth —',
  'v.staff.orType': 'Not in the list? Type its name',
  'v.staff.orTypePlaceholder': 'e.g. Korean Cultural Centre',
  'v.staff.note': 'Anything the organisers should know (optional)',
  'v.staff.send': 'Send request',
  'v.staff.sending': 'Sending…',
  'v.staff.foot': 'Nothing changes on your account until an organiser approves it.',
  'v.staff.pendingTitle': 'Request sent',
  'v.staff.pendingLead': 'An organiser will approve it at the desk. Leave this page open — it updates on its own.',
  'v.staff.pendingBooth': 'You asked for {booth}.',
  'v.staff.pendingNew': 'You asked for a new booth called {booth}.',
  'v.staff.approvedTitle': 'You are in',
  'v.staff.approvedLead': 'Your booth is ready. Open it on the device that will sit on the table.',
  'v.staff.openBooth': 'Open my booth',
  'v.staff.opening': 'Opening…',
  'v.staff.rejected': 'That request was not approved. Speak to an organiser at the desk.',
  'v.staff.alreadyStaff': 'This account already runs a booth.',
  'v.staff.toBooth': 'Open my booth',
  'v.staff.toAdmin': 'Open the dashboard',
  'v.join.staffPrompt': 'Running a booth rather than visiting?',
  'v.join.staffLink': 'Ask for booth access',
  'v.prize.title': 'Prize',
  'v.prize.points': '{n} points',
  'v.prize.visa': 'Entry visa · show this at the prize desk',
  'v.prize.preparing': 'Preparing your code…',
  'v.prize.refresh': 'Refreshes in {n} s — a screenshot will not work. If the camera fails, read out both lines.',
  'v.prize.feedbackEyebrow': 'Before you go · ก่อนกลับ',
  'v.prize.feedbackTitle': 'How was the festival?',
  'v.prize.feedbackTitleTh': 'งานเป็นอย่างไรบ้าง',
  'v.prize.feedbackLead': '{n} questions from the organizers — about two minutes, and it shapes next year’s festival.',
  'v.prize.feedbackLeadTh': '{n} คำถามจากผู้จัดงาน ใช้เวลาประมาณ 2 นาที',
  'v.prize.feedbackCta': 'Answer · ตอบแบบประเมิน',
  'v.prize.feedbackDone': 'Your feedback is with the organizers.',
  'v.prize.next': 'Next',
  'v.prize.collected': 'Collected',
  'v.prize.ready': 'Ready to collect',
  'v.prize.toGo': '{n} to go',
  'v.prize.drawEntry': '+ entry to the closing stage draw',
  'v.prize.runOut': 'This prize has run out',
  'v.prize.left': '{n} left',
  'v.prize.leftSession': '{n} left this {session}',
  'v.prize.leftOfSession': '{n} of {capacity} left this {session}',
  'v.prize.leftOf': '{n} of {capacity} left',
  // Shown while the desk is shut, which before the festival and between sessions is most of the
  // clock. Without it the count simply vanishes and a visitor cannot find out what to expect.
  'v.prize.allowanceClosed': '{n} each session · collect from {time}',
  'v.prize.allowanceEnded': '{n} each session',
  'v.prize.stockLabel': 'Prizes left',
  // The session's own label is admin-set and single-language, so it arrived in Thai copy as the
  // English word. Only the two default windows can be named ahead of time; a custom one still
  // falls back to whatever the organiser typed.
  'v.prize.sessionAm': 'morning',
  'v.prize.sessionPm': 'afternoon',
  'v.prize.collectFrom': 'Collect from {time}',
  'v.prize.deskClosed': 'The prize desk is closed',
  'v.prize.pointsStay': 'Your points stay — collect from {time}.',
  'v.prize.codeLater': 'Your redemption code appears here the moment a tier unlocks. Show it at the prize desk.',

  // festival survey chrome
  'v.survey.title': 'Festival feedback',
  'v.survey.booth': 'Booth',
  'v.survey.opening': 'Opening the questions…',
  'v.survey.thanks': 'Thank you · ขอบคุณ',
  'v.survey.thanksFestival': 'Your feedback is with the organizers.',
  'v.survey.thanksBooth': '{booth} has your answers.',
  'v.survey.backPrize': 'Back to my prize',
  'v.survey.scanAnother': 'Scan another booth',
  'v.survey.myStamps': 'My stamps',
  'v.survey.doneFestival': 'You have already sent your feedback. Thank you.',
  'v.survey.doneBooth': 'You have already answered this booth\u2019s questions. Thank you.',
  'v.survey.noneFestival': 'The feedback form is not open at the moment.',
  'v.survey.noneBooth': 'This booth is not asking anything at the moment.',
  'v.survey.count': '{n} questions',
  'v.survey.noPrizeEffect': 'your prize is not affected by this',
  'v.survey.pointsSaved': 'your stamp and points are already saved',
  'v.survey.submit': 'Submit',
  'v.survey.sending': 'Sending…',
  'v.survey.notNow': 'Not now',
  'v.survey.skip': 'Skip — I would rather keep scanning',
  'v.survey.missing': '{n} required questions still to answer',

  // join
  'v.join.title': 'Start your passport',
  'v.join.lead': 'Under a minute — a few details for the organisers, then your passport opens.',
  'v.join.signedIn': 'Signed in as',
  'v.join.notYou': 'Not you?',
  'v.join.name': 'Your name',
  'v.join.namePlaceholder': 'Shown on your passport cover',
  'v.join.iAm': 'I am a',
  'v.join.type.student': 'Student',
  'v.join.type.staff': 'Staff',
  'v.join.type.alumni': 'Alumni',
  'v.join.type.guest': 'External guest',
  'v.join.id': 'Student / staff ID',
  'v.join.optional': '(optional)',
  'v.join.institution': 'University / institution',
  'v.join.startTyping': 'Start typing…',
  'v.join.choose': '— choose —',
  'v.join.schoolRequired': 'Please choose a school or office.',
  'v.join.institutionName': 'Institution name',
  'v.join.school': 'School / office',
  'v.join.country': 'Country of origin',
  'v.join.otherCountry': 'Other country — search…',
  'v.join.searchCountry': 'Type a country name',
  'v.join.noCountry': 'No country matches that.',
  'v.join.ethnic': 'Ethnic group / community',
  'v.join.ethnicNote': 'MFU serves students from many communities across the Mekong region. The Office of International Affairs asks this only to show, in aggregate, that the festival reached them. It is never shown with your name.',
  'v.join.ethnicPlaceholder': 'Choose, or leave blank',
  'v.join.ethnicOther': 'Something else — type it…',
  'v.join.ethnicOtherLabel': 'Your community',
  'v.join.preferNot': 'Prefer not to say',
  'v.join.ethnicConsent': 'I consent to my ethnic group being collected for aggregate event statistics only.',
  'v.join.ethnicConsentNote': '(Leave unticked and it will not be stored.)',
  'v.join.consent': 'I consent to MFU collecting the details above and my booth check-in times for running this activity and for aggregate event statistics, kept for 90 days after the event.',
  'v.join.privacy': 'Privacy notice',
  'v.join.consentRequired': 'Please tick the consent box to continue.',
  'v.join.create': 'Create my passport',
  'v.join.creating': 'Creating…',
  'common.cancel': 'Cancel',
  'common.saving': 'Saving…',
} as const

export const en = { ...staffEn, ...adminEn }

export type StringKey = keyof typeof en

/** A missing key here is a compile error — that is the point of the explicit type. */
const staffTh: Record<keyof typeof staffEn, string> = {
  'lang.label': 'ภาษา',

  'nav.pages': 'หน้าของบูธ',
  'nav.booth': 'หน้าจอบูธ',
  'nav.stats': 'สถิติ',
  'nav.survey': 'แบบสอบถาม',
  'nav.desk': 'จุดแลกของรางวัล',
  'nav.admin': 'ผู้ดูแลระบบ',
  'nav.account': 'บัญชี',
  'nav.profile': 'โปรไฟล์',
  'nav.myPassport': 'พาสปอร์ตของฉัน',
  'nav.accountSettings': 'ตั้งค่าบัญชี',
  'nav.menu': 'เมนู',
  'nav.signOut': 'ออกจากระบบ',

  'booth.worth': '{location} · ตราประทับนี้มีค่า {points} คะแนน',
  'booth.manualCode': 'รหัสสำหรับกรอกเอง',
  'booth.rotatesIn': 'เปลี่ยนรหัสในอีก',
  'booth.seconds': 'วินาที',
  'booth.visitorsHere': 'ผู้เข้าชมบูธนี้',
  'booth.eventTotal': 'รวมทั้งงาน',
  'booth.rankOf': 'อันดับจาก {count} บูธ',
  'booth.starting': 'กำลังเปิดหน้าจอบูธ…',
  'booth.failed': 'ไม่สามารถเปิดหน้าจอนี้ได้',
  'booth.retry': 'ลองอีกครั้ง',
  'booth.fsUnavailable': 'เบราว์เซอร์นี้ไม่รองรับโหมดเต็มหน้าจอ — กด F11',
  'booth.fsBlocked': 'โหมดเต็มหน้าจอถูกปิดกั้น — กด F11 (⌃⌘F บน Mac)',
  'booth.fsIos': 'iPhone และ iPad ไม่สามารถเปิดโหมดเต็มหน้าจอจากใน Safari ได้ ให้กดปุ่มแชร์ แล้วเลือก “เพิ่มไปยังหน้าจอโฮม” และเปิดหน้าจอบูธจากไอคอนนั้น — จะไม่มีแถบที่อยู่เว็บ',
  'booth.fullScreen': 'เต็มหน้าจอ',
  'booth.exitFullScreen': 'ออกจากโหมดเต็มหน้าจอ',
  'booth.printCard': 'พิมพ์การ์ดบูธ',
  'booth.showCode': 'แสดงรหัสให้ผู้เข้าชม',
  'booth.closeCode': 'กลับสู่หน้าจอบูธ',
  'booth.switchedOff': 'ผู้ดูแลระบบปิดบูธนี้ไว้ — การสแกนของผู้เข้าชมจะไม่ได้รับตราประทับจนกว่าจะเปิดใช้งานอีกครั้ง',
  'booth.notToday': 'วันนี้ไม่มีกำหนดแสดงบนแผนผังตราประทับของผู้เข้าชม — แต่รหัสยังใช้ได้หากมีผู้สแกน',

  'status.live': 'เชื่อมต่ออยู่',
  'status.reconnecting': 'กำลังเชื่อมต่อใหม่',
  'status.offlineCodes': 'ออฟไลน์ — รหัสยังใช้ได้',
  'status.reconnectingCodes': 'กำลังเชื่อมต่อใหม่ — รหัสยังใช้ได้',

  'stats.worth': '{location} · มีค่า {points} คะแนน',
  'stats.visitorsStamped': 'ผู้เข้าชมที่ได้รับตราประทับ',
  'stats.lastAt': 'ครั้งล่าสุด {time}',
  'stats.noneYet': 'ยังไม่มี',
  'stats.perHour': 'ผู้เข้าชมต่อชั่วโมง · วันที่ {day}',
  'stats.day': 'วัน',
  'stats.dayN': 'วันที่ {n}',
  'stats.whoVisited': 'ผู้เข้าชมเป็นใคร',
  'stats.byDay': 'แยกตามวัน',
  'stats.loading': 'กำลังโหลดข้อมูลบูธของคุณ…',
  'stats.noBooth': 'บัญชีนี้ยังไม่ได้ผูกกับบูธใด — โปรดแจ้งผู้ดูแลระบบให้กำหนดบูธให้',
  'stats.boothGone': 'บูธนี้ไม่มีอยู่แล้ว โปรดสอบถามผู้ดูแลระบบว่าบูธของคุณคือบูธใด',

  'account.title': 'บัญชีของคุณ',
  'account.signedIn': 'เข้าสู่ระบบแล้ว',
  'account.back': 'ย้อนกลับ',

  'acct.email.title': 'อีเมล',
  'acct.email.note': 'การเข้าสู่ระบบและการแจ้งเตือนทั้งหมดจะส่งไปที่อีเมลนี้',
  'acct.email.confirmed': 'ยืนยันแล้ว',
  'acct.email.unconfirmed': 'ยังไม่ได้ยืนยัน',
  'acct.email.ok': 'ยืนยันแล้ว',
  'acct.email.pending': 'ยังไม่ยืนยัน',
  'acct.email.change': 'เปลี่ยนอีเมลของฉัน',
  'acct.email.new': 'อีเมลใหม่',
  'acct.email.sendAgain': 'ส่งลิงก์ยืนยันอีกครั้ง',
  'acct.email.send': 'ส่งลิงก์ยืนยัน',
  'acct.email.sending': 'กำลังส่ง…',
  'acct.email.sent': 'ส่งลิงก์ยืนยันแล้ว กดลิงก์ในอีเมล แล้วเปิดหน้านี้อีกครั้ง',

  'acct.pw.title': 'รหัสผ่าน',
  'acct.pw.noteGoogle': 'คุณเข้าสู่ระบบด้วย Google — ตั้งรหัสผ่านเพิ่มได้หากต้องการเข้าสู่ระบบโดยไม่ใช้ Google',
  'acct.pw.noteHas': 'ใช้ร่วมกับอีเมลของคุณเพื่อเข้าสู่ระบบ',
  'acct.pw.add': 'ตั้งรหัสผ่าน',
  'acct.pw.change': 'เปลี่ยนรหัสผ่าน',
  'acct.pw.current': 'รหัสผ่านปัจจุบัน',
  'acct.pw.new': 'รหัสผ่านใหม่',
  'acct.pw.confirm': 'ยืนยันรหัสผ่านใหม่',
  'acct.pw.mismatch': 'รหัสผ่านทั้งสองช่องไม่ตรงกัน',
  'acct.pw.forgot': 'จำรหัสผ่านไม่ได้? ส่งลิงก์ตั้งรหัสผ่านใหม่',
  'acct.pw.changed': 'เปลี่ยนรหัสผ่านแล้ว',
  'acct.pw.added': 'ตั้งรหัสผ่านแล้ว ตอนนี้คุณเข้าสู่ระบบด้วยอีเมลหรือ Google ก็ได้',

  'acct.methods.title': 'วิธีเข้าสู่ระบบ',
  'acct.methods.google': 'Google',
  'acct.methods.password': 'อีเมลและรหัสผ่าน',
  'acct.methods.on': 'เชื่อมต่อแล้ว',
  'acct.methods.off': 'ยังไม่เชื่อมต่อ',
  'acct.pw.none': 'ยังไม่ได้ตั้ง',

  'acct.leaving.title': 'ออกจากระบบ',
  'acct.leaving.note': 'การออกจากระบบไม่ทำให้พาสปอร์ตของคุณหาย ข้อมูลถูกเก็บไว้บนเซิร์ฟเวอร์ เข้าสู่ระบบอีกครั้งจากโทรศัพท์เครื่องใดก็เปิดได้',
  'acct.leaving.signOut': 'ออกจากระบบ',
  'acct.erase.ask': 'ขอให้ลบข้อมูลของฉัน',
  'acct.erase.request': 'ส่งคำขอลบข้อมูล',
  'acct.erase.requested': 'ส่งคำขอลบข้อมูลแล้ว{date} ผู้จัดงานจะลบบัญชีของคุณ และคุณยังใช้พาสปอร์ตได้จนถึงตอนนั้น',
  'acct.erase.on': ' เมื่อ {date}',

  'common.cancel': 'ยกเลิก',
  'common.saving': 'กำลังบันทึก…',
  // ---------- visitor app (pages/visitor/*) ----------
  'v.lang': 'ภาษา / Language',

  'v.tab.cover': 'หน้าปก',
  'v.tab.stamps': 'ตราประทับ',
  'v.tab.prize': 'ของรางวัล',
  'v.tab.profile': 'โปรไฟล์',
  'v.offline': 'ออฟไลน์ — ตราประทับของคุณถูกบันทึกไว้แล้ว',
  'v.offline.note': 'หน้านี้จะอัปเดตเองเมื่อกลับมาออนไลน์ แต่การรับตราใหม่ต้องใช้อินเทอร์เน็ต',
  'v.back.passport': 'พาสปอร์ต',
  'v.back.prize': 'ของรางวัล',
  'v.close': 'ปิด',
  'v.loading': 'กำลังเปิดพาสปอร์ตของคุณ…',

  'v.landing.university': 'มหาวิทยาลัยแม่ฟ้าหลวง',
  'v.landing.badge': 'พาสปอร์ตดิจิทัล',
  'v.landing.pitch': 'สะสมตราประทับจากทุกซุ้มด้วยโทรศัพท์ของคุณเอง สะสมคะแนน แล้วนำไปแลกของรางวัล',
  'v.landing.start': 'เริ่มสร้างพาสปอร์ต',
  'v.landing.have': 'ฉันมีพาสปอร์ตอยู่แล้ว',

  'v.cover.passport': 'พาสปอร์ต',
  'v.cover.pointsStamps': 'คะแนน · {have} จาก {total} ตรา',
  'v.cover.toGo': 'อีก',
  'v.cover.topTier': 'ระดับสูงสุด',
  'v.cover.nextUp': 'ระดับถัดไป',
  'v.cover.allTiers': 'คุณได้รับครบทุกระดับแล้ว นำหน้าของรางวัลไปแสดงที่จุดแลก',
  'v.cover.goHere': 'ไปซุ้มนี้ต่อ',
  'v.cover.points': 'คะแนน',
  'v.cover.allStamped': 'ครบทุกซุ้มแล้ว นำพาสปอร์ตไปที่จุดแลกของรางวัล',
  'v.cover.nothingToday': 'วันนี้ไม่มีซุ้มให้สะสมเพิ่มแล้ว — พรุ่งนี้จะมีซุ้มที่หมุนเวียนมาใหม่',

  'v.stamps.title': 'ตราประทับ',
  'v.stamps.ofTotal': '{have} จาก {total}',
  'v.stamps.progress': 'ประทับแล้ว {have} จาก {total} ซุ้ม',
  'v.stamps.yours': 'ตราประทับของคุณ',
  'v.stamps.none': 'ยังไม่มีตราประทับ กดปุ่มสแกนที่ซุ้มแรกของคุณ',
  'v.stamps.stamped': 'ประทับแล้ว',
  'v.stamps.earning': 'กำลังโหลดคะแนนที่ได้รับ…',
  'v.stamps.plusPts': '+{n} คะแนน',
  'v.stamps.left': 'ยังเหลือให้สะสม',
  'v.stamps.onFloor': 'ยังมีอีก {n} คะแนนในงาน',
  'v.stamps.rewardsNote': 'ของรางวัลอาจเปลี่ยนแปลงได้ คะแนนจะถูกกำหนดเมื่อคุณได้รับตรา เวลาที่แสดงเป็นเวลาประเทศไทย',
  'v.stamps.onlyOn': 'เฉพาะ {days}',
  'v.stamps.pts': '{n} คะแนน',
  'v.stamps.pointsEarned': 'คะแนนที่ได้รับ',
  'v.stamps.pointsWorth': 'คะแนน',
  'v.stamps.present': 'เปิดวัน: {days}',
  'v.stamps.viewFull': 'ดูแบบเต็มจอ',
  'v.stamps.day': 'วันที่ {n}',
  'v.stamps.visa': 'ตราประทับ {booth}',

  'v.scan.title': 'สแกนซุ้ม',
  'v.scan.checkin': 'เช็คอินที่ซุ้ม',
  'v.scan.checking': 'กำลังตรวจสอบ…',
  'v.scan.stamping': 'กำลังประทับตรา…',
  'v.scan.checkingStamp': 'กำลังตรวจสอบตราของคุณ…',
  'v.scan.offline': 'ไม่มีการเชื่อมต่อ ตราประทับต้องบันทึกที่เซิร์ฟเวอร์ จึงต้องใช้สัญญาณสักครู่ — รหัสของซุ้มยังใช้ได้ระหว่างรอ',
  'v.scan.manualLabel': 'หรือพิมพ์รหัส 6 ตัวอักษรที่อยู่ใต้ QR',
  'v.scan.stamp': 'รับตรา',
  'v.scan.aria': 'สแกนซุ้ม',

  'v.res.collected': 'ได้รับตราประทับแล้ว',
  'v.res.plusPoints': '+{n} คะแนน',
  'v.res.summary': '{booth} · รวม {points} คะแนน · {stamps} ตรา',
  'v.res.unlocked': 'คุณปลดล็อกระดับของรางวัลแล้ว ดูที่หน้าของรางวัล',
  'v.res.scanAnother': 'สแกนซุ้มอื่น',
  'v.res.myStamps': 'ตราของฉัน',
  'v.res.already': 'ซุ้มนี้ประทับไปแล้ว',
  'v.res.alreadyNote': '{booth} อยู่ในพาสปอร์ตของคุณแล้ว ลองซุ้มที่ยังไม่เคยไป',
  'v.res.whatsLeft': 'ดูว่าเหลือซุ้มใดบ้าง',
  'v.res.expired': 'รหัสนี้หมดอายุแล้ว — หน้าจอของซุ้มเปลี่ยนทุก 20 วินาที กรุณาสแกนใหม่',
  'v.res.invalid': 'รหัสไม่ถูกต้อง กรุณาส่องกล้องไปที่หน้าจอของซุ้ม หรือพิมพ์รหัส 6 ตัวอักษรใต้ QR',
  'v.res.tooFast': 'เร็วเกินไป — รอสักครู่แล้วลองใหม่',
  'v.res.notRegistered': 'สร้างพาสปอร์ตก่อน แล้วจึงสแกน',
  'v.res.createPassport': 'สร้างพาสปอร์ตของฉัน',
  'v.res.tryAgain': 'ลองใหม่',

  'v.rate.title': 'ซุ้มนี้เป็นอย่างไรบ้าง',
  'v.rate.lead': 'คะแนนของคุณถูกบันทึกแล้ว ส่วนนี้เพียงบอกผู้จัดงานว่าซุ้มนี้เป็นอย่างไร',
  'v.rate.aria': 'ให้คะแนนซุ้มนี้ 1 ถึง 5 ดาว',
  'v.rate.star': '{n} ดาว',
  'v.rate.stars': '{n} ดาว',
  'v.rate.comment': 'อยากบอกอะไรเพิ่มไหม (ไม่บังคับ)',
  'v.rate.placeholder': 'สิ่งที่ประทับใจ หรือสิ่งที่ควรปรับปรุง',
  'v.rate.pick': 'เลือกดาวเพื่อไปต่อ',
  'v.rate.send': 'ส่ง',
  'v.rate.sending': 'กำลังส่ง…',
  'v.rate.thanks': 'ขอบคุณ',
  'v.rate.failed': 'ยังบันทึกคะแนนของคุณไม่ได้ในตอนนี้ — ไปต่อได้เลย ไม่มีอะไรค้างอยู่',
  'v.rate.rated': 'คุณให้ {n} จาก 5 ดาว',

  'v.staff.title': 'ดูแลซุ้มกิจกรรม',
  'v.staff.lead': 'หากคุณเป็นผู้ดูแลซุ้มแต่ไม่ได้รับคำเชิญ สามารถแจ้งได้ที่นี่ ผู้จัดงานจะตรวจสอบและเปลี่ยนสถานะบัญชีของคุณ',
  'v.staff.signInFirst': 'เข้าสู่ระบบด้วยบัญชีใดก็ได้ก่อน แล้วแจ้งว่าซุ้มไหนเป็นของคุณ',
  'v.staff.signIn': 'เข้าสู่ระบบ',
  'v.staff.signUp': 'สร้างบัญชี',
  'v.staff.pickBooth': 'ซุ้มของคุณ',
  'v.staff.pickPlaceholder': '— เลือกซุ้มของคุณ —',
  'v.staff.orType': 'ไม่มีในรายการ? พิมพ์ชื่อซุ้ม',
  'v.staff.orTypePlaceholder': 'เช่น ศูนย์วัฒนธรรมเกาหลี',
  'v.staff.note': 'ข้อมูลเพิ่มเติมถึงผู้จัดงาน (ไม่บังคับ)',
  'v.staff.send': 'ส่งคำขอ',
  'v.staff.sending': 'กำลังส่ง…',
  'v.staff.foot': 'บัญชีของคุณจะยังไม่เปลี่ยนแปลงจนกว่าผู้จัดงานจะอนุมัติ',
  'v.staff.pendingTitle': 'ส่งคำขอแล้ว',
  'v.staff.pendingLead': 'ผู้จัดงานจะอนุมัติที่จุดลงทะเบียน เปิดหน้านี้ทิ้งไว้ ระบบจะอัปเดตให้เอง',
  'v.staff.pendingBooth': 'คุณขอดูแลซุ้ม {booth}',
  'v.staff.pendingNew': 'คุณขอเปิดซุ้มใหม่ชื่อ {booth}',
  'v.staff.approvedTitle': 'เรียบร้อยแล้ว',
  'v.staff.approvedLead': 'ซุ้มของคุณพร้อมใช้งาน เปิดบนอุปกรณ์ที่จะวางไว้ที่ซุ้ม',
  'v.staff.openBooth': 'เปิดซุ้มของฉัน',
  'v.staff.opening': 'กำลังเปิด…',
  'v.staff.rejected': 'คำขอนี้ไม่ได้รับการอนุมัติ กรุณาติดต่อผู้จัดงานที่จุดลงทะเบียน',
  'v.staff.alreadyStaff': 'บัญชีนี้ดูแลซุ้มอยู่แล้ว',
  'v.staff.toBooth': 'เปิดซุ้มของฉัน',
  'v.staff.toAdmin': 'เปิดแดชบอร์ด',
  'v.join.staffPrompt': 'มาดูแลซุ้มไม่ใช่มาร่วมงาน?',
  'v.join.staffLink': 'ขอสิทธิ์ดูแลซุ้ม',
  'v.prize.title': 'ของรางวัล',
  'v.prize.points': '{n} คะแนน',
  'v.prize.visa': 'บัตรผ่าน · แสดงที่จุดแลกของรางวัล',
  'v.prize.preparing': 'กำลังเตรียมรหัสของคุณ…',
  'v.prize.refresh': 'เปลี่ยนใหม่ในอีก {n} วินาที — ภาพหน้าจอใช้ไม่ได้ หากกล้องอ่านไม่ได้ ให้อ่านทั้งสองบรรทัดให้เจ้าหน้าที่ฟัง',
  'v.prize.feedbackEyebrow': 'ก่อนกลับ · Before you go',
  'v.prize.feedbackTitle': 'งานเป็นอย่างไรบ้าง',
  'v.prize.feedbackTitleTh': 'How was the festival?',
  'v.prize.feedbackLead': '{n} คำถามจากผู้จัดงาน ใช้เวลาประมาณ 2 นาที และช่วยกำหนดงานในปีหน้า',
  'v.prize.feedbackLeadTh': '{n} questions from the organizers — about two minutes.',
  'v.prize.feedbackCta': 'ตอบแบบประเมิน · Answer',
  'v.prize.feedbackDone': 'ผู้จัดงานได้รับความคิดเห็นของคุณแล้ว',
  'v.prize.next': 'ระดับถัดไป',
  'v.prize.collected': 'รับแล้ว',
  'v.prize.ready': 'พร้อมให้รับ',
  'v.prize.toGo': 'อีก {n} คะแนน',
  'v.prize.drawEntry': '+ สิทธิ์ร่วมจับรางวัลบนเวทีปิดงาน',
  'v.prize.runOut': 'ของรางวัลนี้หมดแล้ว',
  'v.prize.left': 'เหลืออีก {n} ชิ้น',
  'v.prize.leftSession': 'เหลืออีก {n} ชิ้นในรอบ{session}',
  'v.prize.leftOfSession': 'เหลือ {n} จาก {capacity} ชิ้นในรอบ{session}',
  'v.prize.leftOf': 'เหลือ {n} จาก {capacity} ชิ้น',
  'v.prize.allowanceClosed': 'รอบละ {n} ชิ้น · รับได้ตั้งแต่ {time} น.',
  'v.prize.allowanceEnded': 'รอบละ {n} ชิ้น',
  'v.prize.stockLabel': 'จำนวนของรางวัลที่เหลือ',
  'v.prize.sessionAm': 'เช้า',
  'v.prize.sessionPm': 'บ่าย',
  'v.prize.collectFrom': 'รับได้ตั้งแต่ {time} น.',
  'v.prize.deskClosed': 'จุดแลกของรางวัลปิดอยู่',
  'v.prize.pointsStay': 'คะแนนของคุณยังอยู่ — รับได้ตั้งแต่ {time} น.',
  'v.prize.codeLater': 'รหัสสำหรับแลกของรางวัลจะปรากฏที่นี่ทันทีที่คุณปลดล็อกระดับ นำไปแสดงที่จุดแลก',

  'v.survey.title': 'แบบประเมินงาน',
  'v.survey.booth': 'ซุ้ม',
  'v.survey.opening': 'กำลังเปิดคำถาม…',
  'v.survey.thanks': 'ขอบคุณ · Thank you',
  'v.survey.thanksFestival': 'ผู้จัดงานได้รับความคิดเห็นของคุณแล้ว',
  'v.survey.thanksBooth': '{booth} ได้รับคำตอบของคุณแล้ว',
  'v.survey.backPrize': 'กลับไปหน้าของรางวัล',
  'v.survey.scanAnother': 'สแกนซุ้มอื่น',
  'v.survey.myStamps': 'ตราของฉัน',
  'v.survey.doneFestival': 'คุณส่งความคิดเห็นแล้ว ขอบคุณ',
  'v.survey.doneBooth': 'คุณตอบคำถามของซุ้มนี้แล้ว ขอบคุณ',
  'v.survey.noneFestival': 'ขณะนี้ยังไม่เปิดรับแบบประเมิน',
  'v.survey.noneBooth': 'ขณะนี้ซุ้มนี้ยังไม่มีคำถาม',
  'v.survey.count': '{n} คำถาม',
  'v.survey.noPrizeEffect': 'ไม่มีผลต่อของรางวัลของคุณ',
  'v.survey.pointsSaved': 'ตราและคะแนนของคุณถูกบันทึกแล้ว',
  'v.survey.submit': 'ส่งคำตอบ',
  'v.survey.sending': 'กำลังส่ง…',
  'v.survey.notNow': 'ไว้ภายหลัง',
  'v.survey.skip': 'ข้าม — ขอสแกนต่อก่อน',
  'v.survey.missing': 'ยังมีคำถามที่ต้องตอบอีก {n} ข้อ',

  'v.join.title': 'เริ่มสร้างพาสปอร์ต',
  'v.join.lead': 'ใช้เวลาไม่ถึงหนึ่งนาที กรอกข้อมูลสั้น ๆ สำหรับผู้จัดงาน แล้วพาสปอร์ตของคุณจะเปิดขึ้น',
  'v.join.signedIn': 'เข้าสู่ระบบในชื่อ',
  'v.join.notYou': 'ไม่ใช่คุณ?',
  'v.join.name': 'ชื่อของคุณ',
  'v.join.namePlaceholder': 'ชื่อที่จะแสดงบนหน้าปกพาสปอร์ต',
  'v.join.iAm': 'ฉันคือ',
  'v.join.type.student': 'นักศึกษา',
  'v.join.type.staff': 'บุคลากร',
  'v.join.type.alumni': 'ศิษย์เก่า',
  'v.join.type.guest': 'บุคคลทั่วไป',
  'v.join.id': 'รหัสนักศึกษา / รหัสบุคลากร',
  'v.join.optional': '(ไม่บังคับ)',
  'v.join.institution': 'มหาวิทยาลัย / หน่วยงาน',
  'v.join.startTyping': 'เริ่มพิมพ์…',
  'v.join.choose': '— เลือก —',
  'v.join.schoolRequired': 'กรุณาเลือกสำนักวิชาหรือหน่วยงาน',
  'v.join.institutionName': 'ชื่อหน่วยงาน',
  'v.join.school': 'สำนักวิชา / หน่วยงาน',
  'v.join.country': 'ประเทศที่มาจาก',
  'v.join.otherCountry': 'ประเทศอื่น — ค้นหา…',
  'v.join.searchCountry': 'พิมพ์ชื่อประเทศ',
  'v.join.noCountry': 'ไม่พบประเทศที่ตรงกับคำค้น',
  'v.join.ethnic': 'กลุ่มชาติพันธุ์ / ชุมชน',
  'v.join.ethnicNote': 'มฟล. มีนักศึกษาจากหลากหลายชุมชนทั่วอนุภูมิภาคลุ่มน้ำโขง ส่วนงานการต่างประเทศถามข้อนี้เพียงเพื่อแสดงในภาพรวมว่ากิจกรรมเข้าถึงกลุ่มใดบ้าง และจะไม่แสดงคู่กับชื่อของคุณ',
  'v.join.ethnicPlaceholder': 'เลือก หรือเว้นว่างไว้',
  'v.join.ethnicOther': 'อื่น ๆ — พิมพ์เอง…',
  'v.join.ethnicOtherLabel': 'ชุมชนของคุณ',
  'v.join.preferNot': 'ไม่ประสงค์ระบุ',
  'v.join.ethnicConsent': 'ข้าพเจ้ายินยอมให้เก็บข้อมูลกลุ่มชาติพันธุ์เพื่อใช้เป็นสถิติภาพรวมของงานเท่านั้น',
  'v.join.ethnicConsentNote': '(หากไม่ติ๊ก ระบบจะไม่จัดเก็บข้อมูลนี้)',
  'v.join.consent': 'ข้าพเจ้ายินยอมให้ มฟล. เก็บข้อมูลข้างต้นและเวลาเช็คอินที่ซุ้ม เพื่อใช้ดำเนินกิจกรรมนี้และจัดทำสถิติภาพรวมของงาน โดยเก็บไว้ 90 วันหลังจบงาน',
  'v.join.privacy': 'ประกาศความเป็นส่วนตัว',
  'v.join.consentRequired': 'กรุณาติ๊กช่องยินยอมเพื่อดำเนินการต่อ',
  'v.join.create': 'สร้างพาสปอร์ตของฉัน',
  'v.join.creating': 'กำลังสร้าง…',
}

export const th: Record<StringKey, string> = { ...staffTh, ...adminTh }
