/**
 * The organizer screens that the first Thai pass did not reach — the prize desk, the survey
 * builder and its results, and the redemption landing. The booth screen, its stats and the bar
 * they share were translated earlier and live in `strings.ts`.
 */
export const orgEn = {
  // Redemption landing
  'booth.pointsWhenEarned': 'Points are set when your stamp is earned.',
  'rl.checking': 'Checking…',
  'rl.code': 'Redemption code',

  // Prize desk
  'desk.title': 'Prize desk',
  'desk.checkingBooth': 'Checking your booth…',
  'desk.yourBooth': 'Your booth',
  'desk.notADesk': '{booth} is not a prize desk, so this screen is not yours to run.',
  'desk.openMyBooth': 'Open my booth screen',
  'desk.stock': 'Stock',
  'desk.offline': 'Offline — figures may be old',
  'desk.reconnecting': 'Reconnecting',
  'desk.live': 'Live',
  'desk.opensAt': 'Opens {time}',
  'desk.closed': 'Desk closed',
  'desk.handedOver': 'Handed over',
  'desk.nextVisitor': 'Next visitor',
  'desk.visitor': 'Visitor',
  'desk.done': 'Done',
  'desk.outOfStock': 'Out of stock',
  'desk.confirm': 'Confirm {tier}',
  'desk.handOver': 'Hand over',
  'desk.armedNote': 'Press the gold button again to confirm — a hand-over cannot be undone at the desk.',
  'desk.freshCodePlaceholder': 'New 8-character code',
  'desk.useIt': 'Use it',
  'desk.lookingUp': 'Looking up…',
  'desk.orType': 'Or type what the visitor reads out',
  'desk.codePlaceholder': 'ABCD EFGH',
  'desk.lookUp': 'Look up',
  'desk.onThisDevice': 'Handed over on this device',
  'desk.invalidCode': 'Code expired or not recognised — ask the visitor to show a fresh code, and check the passport number.',
  'desk.deskClosedToday': 'The desk is closed for today. Their points are safe.',
  'desk.outOfStockSession': 'Out of stock for this session.',
  'desk.pointsStayFrom': 'Their points stay — they can collect from {time}.',
  'desk.pointsStay': 'Their points stay.',
  'desk.codeExpired': 'That code has expired. Ask the visitor for the new 8-character code and enter it below.',
  'desk.codeNoted': 'New code noted — press Hand over again.',
  'desk.closedUntil': 'The desk is closed until {time}. Their points are safe — ask them to come back then.',
  'desk.otherDesk': 'The prize desk is {booths}.',
  'desk.pts': '{n} pts',
  'desk.handedOverAt': 'Handed over {time}',
  'desk.handedOverBy': 'Handed over {time} by {who}',

  // Survey results
  'sres.title': 'Survey results',
  'sres.editQuestions': 'Edit the questions',
  'sres.exportCsv': 'Export CSV',
  'sres.responses': 'Responses',
  'sres.ofStamped': 'Of those stamped',
  'sres.collectedStamp': '{n} collected the stamp',
  'sres.status': 'Status',
  'sres.live': 'Live',
  'sres.draft': 'Draft',
  'sres.questionCount': '{n} questions',
  'sres.questionCountOne': '1 question',
  'sres.noQuestions': 'This booth has no questions yet.',
  'sres.buildSurvey': 'Build the survey',
  'sres.andPublish': 'and publish it.',
  'sres.offered': "Visitors are offered the survey after they collect this booth's stamp.",
  'sres.stillDraft': 'The survey is still a draft, so nobody has been asked.',
  'sres.show20': 'Show 20',
  'sres.showAll': 'Show all',
  'sres.when': 'When',
  'sres.nobodyAnswered': 'Nobody answered this one.',

  // Survey builder
  'sb.title': 'Survey',
  'sb.theForm': 'The form',
  'sb.titlePlaceholder': 'Tell us about your visit',
  'sb.description': 'Description',
  'sb.optional': '(optional)',
  'sb.descriptionPlaceholder': 'Two or three questions, about 30 seconds.',
  'sb.headerImage': 'Header image (optional)',
  'sb.addQuestion': 'Add a question',
  'sb.notPublishable': 'Not publishable yet',
  'sb.saving': 'Saving…',
  'sb.save': 'Save',
  'sb.saveAndPublish': 'Save and publish',
  'sb.takeDown': 'Take it down',
  'sb.discard': 'Discard changes',
  'sb.hidePreview': 'Hide preview',
  'sb.preview': 'Preview',
  'sb.previewTitle': 'Preview — exactly what a visitor sees',
  'sb.moveUp': 'Move up',
  'sb.moveDown': 'Move down',
  'sb.duplicate': 'Duplicate',
  'sb.remove': 'Remove',
  'sb.questionPlaceholder': 'What do you want to ask?',
  'sb.helpPlaceholder': 'Help text under the question (optional)',
  'sb.image': 'Image (optional)',
  'sb.options': 'Options',
  'sb.scaleMin': 'Not at all',
  'sb.scaleMax': 'Very much',
  'sb.uploading': 'Uploading…',
  'sb.removeImage': 'Remove image',
  'sb.cancel': 'Cancel',
  'sb.notAnImage': 'That is not an image file.',
  'sb.tooBig': 'Images must be under 2 MB.',
  'sb.savedLive': "Saved and live — visitors see it after they collect this booth's stamp.",
  'sb.savedDraft': 'Saved as a draft. Visitors see nothing until you publish it.',
  'sb.saveFirst': 'Save your changes first — publishing sends whatever is stored, not what is on screen.',
  'sb.liveNow': 'Live now.',
  'sb.takenDown': 'Taken down. Answers already given are kept.',
  'sb.confirmClear': 'Remove every question and unpublish? Answers already collected are kept.',
  'sb.cleared': 'Questions removed. The responses are still under Results.',
} as const

export const orgTh: Record<keyof typeof orgEn, string> = {
  'booth.pointsWhenEarned': 'คะแนนจะถูกกำหนดเมื่อคุณได้รับตราประทับ',
  'rl.checking': 'กำลังตรวจสอบ…',
  'rl.code': 'รหัสแลกของรางวัล',

  'desk.title': 'จุดแลกของรางวัล',
  'desk.checkingBooth': 'กำลังตรวจสอบบูธของคุณ…',
  'desk.yourBooth': 'บูธของคุณ',
  'desk.notADesk': '{booth} ไม่ใช่จุดแลกของรางวัล หน้าจอนี้จึงไม่ใช่หน้าที่ของคุณ',
  'desk.openMyBooth': 'เปิดหน้าจอบูธของฉัน',
  'desk.stock': 'ของรางวัลคงเหลือ',
  'desk.offline': 'ออฟไลน์ — ตัวเลขอาจไม่เป็นปัจจุบัน',
  'desk.reconnecting': 'กำลังเชื่อมต่อใหม่',
  'desk.live': 'เชื่อมต่ออยู่',
  'desk.opensAt': 'เปิด {time}',
  'desk.closed': 'จุดแลกปิดอยู่',
  'desk.handedOver': 'ส่งมอบแล้ว',
  'desk.nextVisitor': 'ผู้เข้าชมคนถัดไป',
  'desk.visitor': 'ผู้เข้าชม',
  'desk.done': 'เสร็จแล้ว',
  'desk.outOfStock': 'ของหมด',
  'desk.confirm': 'ยืนยัน {tier}',
  'desk.handOver': 'ส่งมอบ',
  'desk.armedNote': 'กดปุ่มสีทองอีกครั้งเพื่อยืนยัน — การส่งมอบไม่สามารถย้อนกลับได้ที่จุดแลก',
  'desk.freshCodePlaceholder': 'รหัสใหม่ 8 ตัวอักษร',
  'desk.useIt': 'ใช้รหัสนี้',
  'desk.lookingUp': 'กำลังค้นหา…',
  'desk.orType': 'หรือพิมพ์รหัสที่ผู้เข้าชมอ่านให้ฟัง',
  'desk.codePlaceholder': 'ABCD EFGH',
  'desk.lookUp': 'ค้นหา',
  'desk.onThisDevice': 'ส่งมอบจากอุปกรณ์นี้',
  'desk.invalidCode': 'รหัสหมดอายุหรือไม่ถูกต้อง — ขอให้ผู้เข้าชมแสดงรหัสใหม่ และตรวจสอบหมายเลขพาสปอร์ต',
  'desk.deskClosedToday': 'จุดแลกของรางวัลปิดแล้วสำหรับวันนี้ คะแนนของเขายังอยู่ครบ',
  'desk.outOfStockSession': 'ของรางวัลในรอบนี้หมดแล้ว',
  'desk.pointsStayFrom': 'คะแนนยังอยู่ — รับได้ตั้งแต่ {time}',
  'desk.pointsStay': 'คะแนนของเขายังอยู่',
  'desk.codeExpired': 'รหัสนี้หมดอายุแล้ว ขอรหัสใหม่ 8 ตัวอักษรจากผู้เข้าชม แล้วกรอกด้านล่าง',
  'desk.codeNoted': 'บันทึกรหัสใหม่แล้ว — กดส่งมอบอีกครั้ง',
  'desk.closedUntil': 'จุดแลกของรางวัลปิดจนถึง {time} คะแนนของเขายังอยู่ครบ — แจ้งให้กลับมาใหม่ตอนนั้น',
  'desk.otherDesk': 'จุดแลกของรางวัลคือ {booths}',
  'desk.pts': '{n} คะแนน',
  'desk.handedOverAt': 'ส่งมอบเมื่อ {time}',
  'desk.handedOverBy': 'ส่งมอบเมื่อ {time} โดย {who}',

  'sres.title': 'ผลแบบสอบถาม',
  'sres.editQuestions': 'แก้ไขคำถาม',
  'sres.exportCsv': 'ส่งออก CSV',
  'sres.responses': 'จำนวนผู้ตอบ',
  'sres.ofStamped': 'จากผู้ที่รับตราประทับ',
  'sres.collectedStamp': 'รับตราประทับแล้ว {n} คน',
  'sres.status': 'สถานะ',
  'sres.live': 'เผยแพร่อยู่',
  'sres.draft': 'ฉบับร่าง',
  'sres.questionCount': '{n} คำถาม',
  'sres.questionCountOne': '1 คำถาม',
  'sres.noQuestions': 'บูธนี้ยังไม่มีคำถาม',
  'sres.buildSurvey': 'สร้างแบบสอบถาม',
  'sres.andPublish': 'แล้วเผยแพร่',
  'sres.offered': 'ผู้เข้าชมจะเห็นแบบสอบถามหลังจากรับตราประทับของบูธนี้',
  'sres.stillDraft': 'แบบสอบถามยังเป็นฉบับร่าง จึงยังไม่มีใครได้รับคำถาม',
  'sres.show20': 'แสดง 20 รายการ',
  'sres.showAll': 'แสดงทั้งหมด',
  'sres.when': 'เวลา',
  'sres.nobodyAnswered': 'ยังไม่มีใครตอบข้อนี้',

  'sb.title': 'แบบสอบถาม',
  'sb.theForm': 'แบบฟอร์ม',
  'sb.titlePlaceholder': 'เล่าให้เราฟังเกี่ยวกับการเข้าชมของคุณ',
  'sb.description': 'คำอธิบาย',
  'sb.optional': '(ไม่บังคับ)',
  'sb.descriptionPlaceholder': 'สองถึงสามคำถาม ใช้เวลาประมาณ 30 วินาที',
  'sb.headerImage': 'ภาพหัวเรื่อง (ไม่บังคับ)',
  'sb.addQuestion': 'เพิ่มคำถาม',
  'sb.notPublishable': 'ยังเผยแพร่ไม่ได้',
  'sb.saving': 'กำลังบันทึก…',
  'sb.save': 'บันทึก',
  'sb.saveAndPublish': 'บันทึกและเผยแพร่',
  'sb.takeDown': 'นำออกจากการเผยแพร่',
  'sb.discard': 'ยกเลิกการแก้ไข',
  'sb.hidePreview': 'ซ่อนตัวอย่าง',
  'sb.preview': 'ดูตัวอย่าง',
  'sb.previewTitle': 'ตัวอย่าง — ตรงกับที่ผู้เข้าชมเห็นทุกประการ',
  'sb.moveUp': 'เลื่อนขึ้น',
  'sb.moveDown': 'เลื่อนลง',
  'sb.duplicate': 'ทำสำเนา',
  'sb.remove': 'ลบ',
  'sb.questionPlaceholder': 'คุณอยากถามอะไร?',
  'sb.helpPlaceholder': 'ข้อความอธิบายใต้คำถาม (ไม่บังคับ)',
  'sb.image': 'รูปภาพ (ไม่บังคับ)',
  'sb.options': 'ตัวเลือก',
  'sb.scaleMin': 'ไม่เลย',
  'sb.scaleMax': 'มากที่สุด',
  'sb.uploading': 'กำลังอัปโหลด…',
  'sb.removeImage': 'ลบรูปภาพ',
  'sb.cancel': 'ยกเลิก',
  'sb.notAnImage': 'ไฟล์นี้ไม่ใช่รูปภาพ',
  'sb.tooBig': 'รูปภาพต้องมีขนาดไม่เกิน 2 MB',
  'sb.savedLive': 'บันทึกและเผยแพร่แล้ว — ผู้เข้าชมจะเห็นหลังรับตราประทับของบูธนี้',
  'sb.savedDraft': 'บันทึกเป็นฉบับร่างแล้ว ผู้เข้าชมจะยังไม่เห็นจนกว่าคุณจะเผยแพร่',
  'sb.saveFirst': 'กรุณาบันทึกการแก้ไขก่อน — การเผยแพร่จะใช้ข้อมูลที่บันทึกไว้ ไม่ใช่สิ่งที่แสดงบนหน้าจอ',
  'sb.liveNow': 'เผยแพร่แล้ว',
  'sb.takenDown': 'นำออกจากการเผยแพร่แล้ว คำตอบที่ได้รับไว้ยังถูกเก็บไว้',
  'sb.confirmClear': 'ลบคำถามทั้งหมดและหยุดเผยแพร่ใช่หรือไม่? คำตอบที่เก็บไว้แล้วจะยังคงอยู่',
  'sb.cleared': 'ลบคำถามแล้ว คำตอบยังดูได้ที่หน้าผลแบบสอบถาม',
}
