/**
 * The admin console, in both languages.
 *
 * A separate file from `strings.ts` purely for size: the staff screens are 99 strings and this
 * is three times that, and one 1,000-line dictionary is harder to hand to somebody for review
 * than two files split along the seam the product already has. Both halves are merged in
 * `strings.ts`, and `th` there is still declared `Record<keyof typeof en, string>`, so a key
 * added here without a Thai value remains a *build* error rather than an English word surfacing
 * in a Thai interface during the festival.
 *
 * Why this exists at all: `spec §1.4` chose an English interface because the visitors this
 * festival exists to bring together do not share Thai. That reasoning covers the passport and
 * the booth screens; it does not cover this console, whose users are MFU staff. `strings.ts`
 * used to say the admin panel "stays English" — the toggle in the account menu therefore
 * changed the heading font and nothing else, which reads as a bug rather than a decision.
 *
 * Register: plain administrative Thai, the vocabulary a university office actually uses.
 * `{placeholders}` are filled by `t('key', { … })`.
 */
export const adminEn = {
  // ---------- enum labels (lib/labels.ts) ----------
  'label.zone.entrance': 'Entrance row',
  'label.zone.middle': 'Middle hall',
  'label.zone.far': 'Far corner',
  'label.role.visitor': 'Visitor',
  'label.role.organizer': 'Booth organizer',
  'label.role.admin': 'Admin',
  'label.visitorType.student': 'Student',
  'label.visitorType.staff': 'Staff',
  'label.visitorType.alumni': 'Alumni',
  'label.visitorType.guest': 'Guest',

  // ---------- the console shell (AdminLayout) ----------
  'admin.title': 'Passport admin',
  'admin.rail.brand': 'Admin',
  'admin.menu': 'Menu',
  'admin.rail.expand': 'Expand the sidebar',
  'admin.rail.collapse': 'Collapse the sidebar',
  'admin.group.run': 'Run',
  'admin.group.setup': 'Set up',
  'admin.group.records': 'Records',
  'admin.group.screens': 'Screens',
  'admin.nav.dashboard': 'Dashboard',
  'admin.nav.draw': 'Stage draw',
  'admin.nav.event': 'Event',
  'admin.nav.booths': 'Booths',
  'admin.nav.prizes': 'Prizes & stock',
  'admin.nav.users': 'Users & invites',
  'admin.nav.audit': 'Audit log',
  'admin.nav.refdata': 'Reference lists',
  'admin.nav.ratings': 'Booth ratings',
  'admin.nav.feedback': 'Festival feedback',
  'admin.nav.wall': 'Hall screen',
  'admin.nav.desk': 'Prize desk',

  // ---------- first-admin setup (Setup) ----------
  'setup.title': 'First-admin setup',
  'setup.signedInAs': 'Signed in as',
  'setup.becomesAdmin': '— this is the account that becomes admin.',
  'setup.keyBefore': 'Enter the bootstrap key you set with',
  'setup.keyAfter': 'Works once — while no admin exists yet. Add further admins from the admin panel.',
  'setup.already': 'This account is already an admin.',
  'setup.yourName': 'Your name',
  'setup.key': 'Bootstrap key',
  'setup.submit': 'Make me admin',

  // ---------- printable booth cards (BoothCards) ----------
  'boothCards.hint': '{count} cards, one per page. Print on A4, or choose “Save as PDF”.',
  'boothCards.hintOne': 'One card, on its own page. Print on A4, or choose “Save as PDF”.',
  'boothCards.printAll': 'Print all',
  'boothCards.back': 'Back',
  'boothCards.none': 'No active booths.',

  // ---------- go-live checklist (Readiness) ----------
  'readiness.title': 'Ready for the event?',
  'readiness.of': '{done} of {total}',
  'readiness.starts': 'Starts {when}',
  'readiness.hide': 'Hide',
  'readiness.booths': 'At least one active booth',
  'readiness.boothsDetail': '{count} active',
  'readiness.prizes': 'A prize policy is saved',
  'readiness.prizesDetail': '{count} tiers',
  'readiness.organizers': 'Every active booth has an organizer linked',
  'readiness.organizersDetail': '{count} without: {names}',
  'readiness.signIn': 'Your admin account can sign in on another device',
  'readiness.signInDetail': 'a password or Google',
  'readiness.mail': 'Invitation email',
  'readiness.mailOk': 'Invitation email is configured',
  'readiness.mailNo': 'Invitation email is not configured',
  'readiness.mailChecking': 'checking…',
  'readiness.mailDetail': 'invites show a copyable link instead — fine for a small team',

  // ---------- audit log (Audit) ----------
  'audit.title': 'Audit log',
  'audit.lead': 'Every admin action, newest first. Showing {shown}.',
  'audit.ofTotal': '{shown} of {total}',
  'audit.filterAction': 'Filter by action',
  'audit.allActions': 'All actions',
  'audit.search': 'Search target, actor…',
  'audit.searchLabel': 'Search',
  'audit.csv': 'CSV (contains personal data)',
  'audit.csvConfirm': 'This export includes before/after values from user edits, which contain contact details. Continue?',
  'audit.when': 'When',
  'audit.action': 'Action',
  'audit.target': 'Target',
  'audit.actor': 'Actor',
  'audit.change': 'Change',
  'audit.diff': 'diff',
  'audit.noMatch': 'Nothing matches',
  'audit.none': 'Nothing yet',
  'audit.loadMore': 'Load {count} more',

  // ---------- stage draw (Draw) ----------
  'draw.title': 'Stage draw',
  'draw.lead': 'Picks at random from visitors holding a tier that grants a draw entry. Everyone already drawn is excluded, and every draw is logged.',
  'draw.noTierBefore': 'No tier grants a draw entry yet, so there is nobody to draw from. Tick',
  'draw.noTierTick': 'Stage draw entry',
  'draw.noTierAfter': 'on a tier in Prizes & stock.',
  'draw.inHat': 'in the hat',
  'draw.alreadyDrawn': 'already drawn, excluded',
  'draw.grantsEntry': 'grants the entry',
  'draw.winners': 'Winners',
  'draw.drawing': 'Drawing…',
  'draw.draw': 'Draw',
  'draw.confirm': 'Draw {count} more winners? Everyone already drawn stays out, and this is logged as a separate draw.',
  'draw.revealBefore': 'The reveal plays on the',
  'draw.revealLink': 'hall screen ↗',
  'draw.revealAfter': ', which takes over from the live stats for a minute and then returns to them.',
  'draw.range': 'Choose between 1 and 20 winners.',
  'draw.noneEligible': 'Nobody is eligible right now.',
  'draw.allDrawn': 'Everyone who qualified has already been drawn.',
  'draw.noneQualified': 'No visitor has reached a tier that grants an entry yet.',
  'draw.onScreenNow': 'On the hall screen now',
  'draw.foundNobody': 'That draw found nobody eligible.',
  'draw.drawnFrom': 'Drawn from {count} entries at {when}.',
  'draw.everyDraw': 'Every draw',
  'draw.thWinner': 'Winner',
  'draw.thPassport': 'Passport',
  'draw.thPool': 'Pool',

  // ---------- reference lists (RefData) ----------
  'refData.title': 'Reference lists',
  'refData.lead': 'What the registration form suggests. Editable here so the lists can change during the event without a redeploy — they used to be settable only by re-running the seed script.',
  'refData.tab.institutions': 'Institutions',
  'refData.tab.schools': 'MFU schools',
  'refData.tab.ethnic': 'Ethnic groups',
  'refData.blurb.institutions': 'Universities offered in the registration form. Visitors can still type anything — this is a suggestion list.',
  'refData.blurb.schools': 'Offered when a visitor picks MFU as their institution.',
  'refData.blurb.ethnic': 'Per country of origin. Sensitive data under PDPA s.26: optional for the visitor, gated behind its own consent, never shown per person, and suppressed below 5 in aggregate. The Office of International Affairs owns this wording.',
  'refData.discard': 'Discard the unsaved changes on this list?',
  'refData.savedCountries': 'Saved {count} countries. The registration form picks this up immediately.',
  'refData.savedEntries': 'Saved {count} entries. The registration form picks this up immediately.',
  'refData.removeCountry': 'Remove country',
  'refData.addCountry': 'Add a country (ISO code)',
  'refData.add': 'Add',
  'refData.onePerLine': 'One per line · {count} entries',
  'refData.sortNote': 'Saved sorted alphabetically, with duplicates and blank lines dropped.',
  'refData.keepOther': 'Keep "Other" in the list — the form shows a free-text box when it is chosen.',
  'common.save': 'Save',
  'common.discardChanges': 'Discard changes',

  // ---------- printable report (Print) ----------
  'print.hint': 'In the print dialog choose “Save as PDF” for the report. Landscape is not needed.',
  'print.print': 'Print / Save as PDF',
  'print.back': 'Back',
  'print.title': 'Passport dashboard',
  'print.allDays': 'All days',
  'print.day': 'Day {n}',
  'print.generated': 'Generated {when}',
  'print.countersLive': 'counters live',
  'print.countersAge': 'counters {min} min old',
  'print.visitors': 'Visitors registered',
  'print.stamps': 'Stamps collected',
  'print.redeemed': 'Prizes redeemed',
  'print.active15': 'Active last 15 min',
  'print.leaderboard': 'Booth leaderboard',
  'print.noBooths': 'No booths',
  'print.perFive': 'Stamps per 5 minutes',
  'print.noScans': 'No scans yet',
  'print.countries': 'Countries · {count} represented',
  'print.noRegistrations': 'No registrations yet',
  'print.participation': 'Participation',
  'print.thai': 'Thai',
  'print.international': 'International',
  'print.funnelTitle': 'Visitor funnel',
  'print.institutions': 'Institutions',
  'print.schools': 'MFU schools',
  'print.stock': 'Prize stock',
  'print.cross': 'Cross-school · visitor’s school × booth',
  'print.school': 'School',
  'print.ethnic': 'Ethnic groups · aggregate · {rate}% response',
  'print.footer': 'Aggregates only — no personal data. Ethnic groups under 5 are folded into “Other” and the panel is omitted entirely below 20 consenting visitors.',
  'print.nothingYet': 'Nothing yet',
  'funnel.registered': 'Registered',
  'funnel.oneStamp': '1+ stamp',
  'funnel.tierReached': 'Tier reached',
  'funnel.redeemed': 'Redeemed',

  // ---------- hall screen (Wall) ----------
  'wall.title': 'Passport live',
  'wall.adminConsole': 'Admin console',
  'wall.drawing': 'Drawing',
  'wall.winner': 'Winner',
  'wall.winners': 'Winners',
  'wall.nobodyEligible': 'Nobody was eligible.',
  'wall.visitors': 'Visitors',
  'wall.stamps': 'Stamps',
  'wall.prizes': 'Prizes',
  'wall.joinHere': 'Start your passport',
  'wall.step1': 'Scan the QR',
  'wall.step2': 'Collect a stamp at every booth',
  'wall.step3': 'Trade your points for a prize',
  'wall.busiest': 'Busiest booths right now',
  'wall.drawnFrom': 'Drawn from {n} entries',
  'wall.pressF': 'Press F for full screen',
  'wall.fsIos': 'iPhone and iPad cannot go full screen from inside Safari. Tap Share, then “Add to Home Screen”, and open the hall screen from that icon.',

  // ---------- live dashboard (Dashboard) ----------
  'dash.title': 'Dashboard',
  'dash.live': 'Live',
  'dash.connected': 'connected',
  'dash.reconnecting': 'reconnecting',
  'dash.countersAge': 'counters {min} min old',
  'dash.daySelector': 'Day selector',
  'dash.allDays': 'All',
  'dash.printPdf': 'Print / PDF',
  'dash.leaderboard': 'Booth leaderboard',
  'dash.topBooth': '★ top booth',
  'dash.needsTraffic': 'needs traffic',
  'dash.countries': 'Countries · {count} represented',
  'dash.institutions': 'Institutions · MFU schools',
  'dash.cross': 'Cross-school · who visits whose booth',
  'dash.manage': 'Manage',
  'dash.ethnic': 'Ethnic groups · aggregate only',
  'dash.ethnicConfirm': 'This export contains aggregate ethnic-group counts (groups under 5 are already folded into Other). It is sensitive data under PDPA s.26 — continue?',
  'dash.ethnicHidden': 'Shown once at least 20 visitors have consented ({count} so far). Groups under 5 are folded into "Other".',
  'dash.ethnicRate': 'Response rate {rate}% · groups under 5 folded into Other',
  'dash.crossEmpty': 'Appears once visitors start scanning.',
  'dash.crossHeader': 'Visitor’s school ↓ · booth →',
  'dash.crossNote': 'Gold ring = a school’s own booth. Filled cells elsewhere in the row mean visitors left their own booth.',

  // ---------- prizes and stock (Prizes) ----------
  'prizes.title': 'Prizes & stock',
  'prizes.counting': 'Counting base points…',
  'prizes.floor': '{points} base points across {booths} active booths. A threshold above that is refused, and one within 10 of it is flagged. Temporary booth adjustments do not change this policy limit.',
  'prizes.saved': 'Policy saved. Lowered thresholds unlocked immediately; raised ones revoked nothing.',
  'prizes.previewOnly': 'Preview only — nothing saved. The effect is shown under each tier.',
  'prizes.remoteChanged': 'Another admin changed the prize policy while you were editing.',
  'prizes.discardMine': 'Discard my edits',
  'prizes.thenLoad': 'to load theirs, or save to overwrite.',
  'prizes.tiers': 'Tiers',
  'prizes.unsaved': 'Unsaved changes',
  'prizes.newTier': 'New tier',
  'prizes.drawEntry': 'Draw entry',
  'prizes.ofLeft': 'of {total} left',
  'prizes.name': 'Name',
  'prizes.namePlaceholder': 'Explorer',
  'prizes.unlocksAt': 'Unlocks at',
  'prizes.points': 'points',
  'prizes.reward': 'Reward',
  'prizes.rewardPlaceholder': 'Tote bag',
  'prizes.initialStock': 'Initial stock',
  'prizes.stageDrawEntry': 'Stage draw entry',
  'prizes.addNote': 'Add a sold-out message',
  'prizes.noteLabel': 'Shown to visitors once it runs out',
  'prizes.notePlaceholder': 'e.g. Collect from the information desk after 15:00',
  'prizes.thisTier': 'This tier',
  'prizes.remove': 'Remove',
  'prizes.removeOnSave': 'Remove on save',
  'prizes.willDeactivateOne': '{names} will be deactivated when you save. Visitors who already unlocked it keep the unlock.',
  'prizes.willDeactivateMany': '{names} will be deactivated when you save. Visitors who already unlocked them keep the unlock.',
  'prizes.addTier': 'Add tier',
  'prizes.checking': 'Checking…',
  'prizes.previewEffect': 'Preview effect',
  'prizes.adjust': 'Adjust stock',
  'prizes.adjustLead': 'Counts are never typed over. Every change is a signed adjustment with a reason, so the closing figures reconcile with what was loaded in.',
  'prizes.tier': 'Tier',
  'prizes.tierPlaceholder': '— tier —',
  'prizes.kind': 'Kind',
  'prizes.restock': 'Restock (+)',
  'prizes.correction': 'Correction (±)',
  'prizes.delta': 'Change (whole number, e.g. 50 or -3)',
  'prizes.reasonLedger': 'Reason (kept in the ledger)',
  'prizes.applying': 'Applying…',
  'prizes.apply': 'Apply adjustment',
  'prizes.adjusted': 'Stock adjusted by {delta} and logged.',
  'prizes.perSession': '{n} per session',
  'prizes.allowance': 'Per-session allowance',
  'prizes.allowanceLead': 'How many each session starts with. Applies to every session nobody has collected from yet — a session already under way keeps the number it is on, including the one open now. To add gifts to the session open right now, use Add stock above.',
  'prizes.allowanceField': 'Gifts per session',
  'prizes.allowanceApply': 'Set allowance',
  'prizes.allowanceSetting': 'Setting…',
  'prizes.allowanceSet': 'Allowance changed from {from} to {to} per session, and logged.',
  'prizes.recent': 'Recent adjustments',
  'prizes.noAdjustments': 'No adjustments yet. Stock stands at what the seed loaded in.',
  'prizes.void': 'Void a redemption',
  'prizes.voidLeadBefore': 'Returns the item to stock and lets that visitor collect again. Easier from',
  'prizes.voidLeadAfter': ': open the visitor and press',
  'prizes.voidLeadEnd': 'beside the prize. This form needs the user ID shown there.',
  'prizes.userId': 'User ID',
  'prizes.reasonAudit': 'Reason (kept in the audit log)',
  'prizes.voiding': 'Voiding…',
  'prizes.voidBtn': 'Void redemption…',
  'prizes.voidConfirm': 'Void {tier} for visitor {uid}? The item returns to stock and the visitor can collect again.',
  'prizes.voidThisTier': 'this tier',
  'prizes.voided': 'Redemption voided; item returned to stock.',
  'prizes.users': 'Users',
  'prizes.voidWord': 'Void',

  // ---------- prizes — inline hints ----------
  'prizes.within10': 'Within 10 of the {points} on the floor.',
  'prizes.unlocksFor': 'Unlocks for {count} visitors.',

  // ---------- booths (Booths) ----------
  'booths.title': 'Booths',
  'booths.printAll': 'Print all cards',
  'booths.new': 'New booth',
  'booths.editTitle': 'Edit · {name}',
  'booths.nameEn': 'Name (English)',
  'booths.nameTh': 'Name (Thai, optional)',
  'booths.shortName': 'Short name on stamp',
  'booths.hostUnit': 'Host unit',
  'booths.location': 'Location',
  'booths.zone': 'Zone',
  'booths.order': 'Order in the grid',
  'booths.orderPlaceholder': 'next free',
  'booths.accent': 'Accent',
  'booths.accentAria': 'Accent {colour}',
  'booths.stampPreview': 'Stamp preview',
  'booths.description': 'Description',
  'booths.presentOn': 'Present on',
  'booths.isPrizeDesk': 'This booth is a prize desk',
  'booths.active': 'Active',
  'booths.create': 'Create booth',
  'booths.cancel': 'Cancel',
  'booths.filter': 'Filter by name, host, location, zone',
  'booths.filterAria': 'Filter booths',
  'booths.unstaffedOnly': 'Without an organizer only',
  'booths.shownOf': '{shown} of {total}',
  'booths.none': 'No booths yet — press New booth.',
  'booths.noMatch': 'No booth matches.',
  'booths.days': '{done}/{total} days',
  'booths.prizeDesk': 'prize desk',
  'booths.inactive': 'inactive',
  'booths.keep': 'Keep for this event',
  'booths.delete': 'Delete',
  'booths.edit': 'Edit',
  'booths.openScreen': 'Open screen',
  'booths.stats': 'Stats',
  'booths.moreActions': 'More actions for {name}',
  'booths.more': 'More ▾',
  'booths.replaceBadge': 'Replace badge…',
  'booths.uploadBadge': 'Upload badge…',
  'booths.removeBadge': 'Remove badge',
  'booths.replacePhoto': 'Replace photo…',
  'booths.uploadPhoto': 'Upload photo…',
  'booths.removePhoto': 'Remove photo',
  'booths.rotateSecret': 'Rotate secret…',
  'booths.deleteBooth': 'Delete booth…',
  'booths.rotateConfirm': 'Rotate the secret of {name}? Every code currently on its screen or in a photo stops working immediately.',
  'booths.deleteConfirm': 'Delete {name}? If it already has stamps it will be deactivated instead.',
  'booths.badgeTooBig': 'Badge must be under 512 KB',
  'booths.photoTooBig': 'Photo must be under 2 MB',
  'booths.removeBadgeConfirm': 'Remove the badge of {name}? The generated stamp takes over.',
  'booths.removePhotoConfirm': 'Remove the photo of {name}?',
  'booths.bulk': 'Bulk: paste a list of booths',
  'booths.bulkLine': 'One booth per line:',
  'booths.bulkCols': ', with an optional fifth column for points.',
  'booths.bulkZone': 'Zone is',
  'booths.bulkZoneAfter': '({entrance} / {middle} / {far} points by default). Badges, days and the prize-desk flag are set on the cards afterwards.',
  'booths.bulkAria': 'Booth list',
  'booths.bulkBad': '{count} lines need a name and a zone of entrance / middle / far: {lines}',
  'booths.bulkCreate': 'Create {count} booths',
  'booths.bulkProgress': 'Creating {n} of {total}…',
  'booths.bulkFailed': '{made} created, {failed} failed — {detail}',
  'booths.bulkDone': '{count} booths created.',
  'booths.organizer': 'organizer',
  'booths.invited': 'Invited',
  'booths.resend': 'Resend',
  'booths.organizerName': 'Organizer name',
  'booths.organizerEmail': 'Organizer email',
  'booths.name': 'Name',
  'booths.email': 'Email',
  'booths.sending': 'Sending…',
  'booths.send': 'Send',
  'booths.noOrganizer': 'No organizer yet',
  'booths.inviteOrganizer': 'Invite organizer',
  'booths.inviteLink': 'Invitation link',
  'booths.showLink': 'Show the link anyway',
  'booths.mailed': 'Invitation emailed to {email}.',
  'booths.mailOff': 'Email is not configured — copy the link under {name} and send it yourself.',
  'booths.resent': 'Re-sent to {email}.',
  'booths.resentLink': 'New link ready under {name} — copy it. The old link no longer works.',

  // ---------- event lifecycle (Event) ----------
  'event.title': 'Event',
  'event.loading': 'Loading events…',
  'event.current': 'The current event',
  'event.draft': 'Draft · {id}',
  'event.newEvent': 'New event (starts as a draft)',
  'event.backToCurrent': 'Back to the current event',
  'event.nameEn': 'Name (English)',
  'event.nameTh': 'Name (Thai, optional)',
  'event.starts': 'Starts',
  'event.ends': 'Ends',
  'event.days': 'Days the event runs',
  'event.dayN': 'Day {n}',
  'event.qrPeriod': 'QR rotation (seconds)',
  'event.qrRange': '10 to 120 seconds',
  'event.prefix': 'Passport prefix',
  'event.prefixHint': 'Numbers read {prefix}-0001',
  'event.zonePoints': 'Default points per zone',
  'event.zoneNote': 'Applies to booths created from now on. Existing booths keep their points, and points already awarded are frozen at scan time.',
  'event.prizeSessions': 'Prize collection windows',
  'event.prizeSessionsNote': 'Each window has its own stock of gifts. A window gates the gift, never the points: someone who qualifies while the desk is shut keeps every point and collects in the next window. If the desk has to hand over outside a window, widen the window here rather than working around it.',
  'event.sessionLabel': 'Name',
  'event.sessionFrom': 'From',
  'event.sessionTo': 'To',
  'event.addSession': 'Add a window',
  'event.removeSession': 'Remove',
  'event.sessionOverlap': 'Windows cannot overlap, and each must end after it starts.',
  'event.createDraft': 'Create draft',
  'event.unsaved': 'Unsaved changes',
  'event.goLive': 'Go live',
  'event.saved': 'Event saved.',
  'event.created': 'Created "{id}" as a draft. Add booths and a prize policy, then Go live.',
  'event.nowLive': 'This event is now live.',
  'event.deleteDraftConfirm': 'Delete the draft "{name}"? This cannot be undone.',
  'event.draftDeleted': 'Draft "{id}" deleted.',
  'event.after': 'After the event · archive this one, prepare the next',
  'event.afterLead': 'Booths, prizes and accounts are shared, not copied per event. The way to move on is to archive the current event (its totals are frozen), which clears stamps and progress, then go live with the next one. A draft can be prepared here in advance, but only its own settings: booths and prizes stay as they are until you archive.',
  'event.newDraft': 'New draft event',
  'event.all': 'All events',
  'event.edit': 'Edit',
  'event.deleteDraft': 'Delete draft',
  'event.danger': 'Danger zone',
  'event.dangerBefore': 'Archive',
  'event.dangerAfter': 'and start a new event. Its totals are frozen to a read-only archive first, then the stamps, prize unlocks, counters and visitor progress are cleared so the next event starts from zero. This cannot be undone.',
  'event.archiveStart': 'Archive & start a new event',
  'event.keepBooths': 'Keep the booths (counters reset to zero and every QR secret is replaced)',
  'event.keepTiers': 'Keep the prize policy (stock restored to the full loaded-in figure)',
  'event.hardDelete': 'Also delete visitor accounts outright (PDPA). Otherwise their progress is reset and the account kept.',
  'event.typeToConfirm': 'Type',
  'event.toConfirm': 'to confirm',
  'event.working': 'Working…',
  'event.archiveClear': 'Archive and clear',
  'event.cancel': 'Cancel',
  'event.clearedBefore': 'Cleared. The archive is at',
  'event.clearedAfter': 'Now create the next event above',
  'event.clearedBooths': ', add its booths',
  'event.clearedTiers': ' and set a prize policy',
  'event.clearedThen': ', then press',
  'event.freezing': 'Freezing totals to the archive…',
  'event.archived': 'Archived — {visitors} visitors, {stamps} stamps, {prizes} prizes handed over',
  'event.settling': 'Settling counters…',
  'event.settled': 'Settling counters — done',
  'event.stepBoothStats': 'Reset booth counters',
  'event.stepRotate': 'New booth QR secrets',
  'event.stepBooths': 'Booths and artwork',
  'event.stepResetStock': 'Restore prize stock',
  'event.stepTiers': 'Prize tiers',
  'event.scope.scans': 'Stamps',
  'event.scope.tierUnlocks': 'Prize unlocks',
  'event.scope.stockAdjustments': 'Stock ledger',
  'event.scope.draws': 'Stage draws',
  'event.scope.buckets': 'Timeline',
  'event.scope.invites': 'Invitations',
  'event.scope.rateLimits': 'Rate limits',
  'event.scope.counters': 'Passport numbering',
  'event.scope.visitors': 'Visitor progress',
  'event.scope.eventStats': 'Event counters',

  // ---------- users and invitations (Users) ----------
  'users.title': 'Users & invitations',
  'users.makeAdminConfirm': 'Make {name} an admin? They will be able to change every setting.',
  'users.demoteConfirm': 'Demote {name} to a visitor? Their booth screen and desk stop working within 15 minutes.',
  'users.deleteConfirm': 'Delete {name}? Contact details are anonymised and the account is disabled; scan rows are kept for statistics.',
  'users.deleted': 'Deleted (soft): anonymised and disabled.',
  'users.dismissed': 'Request dismissed and logged.',
  'users.invitesSent': '{count} invitations emailed.',
  'users.mailOff': 'Email is not configured yet — copy each link below and send it to the organizer yourself.',
  'users.mailFailed': 'Email did not go out for {failed} of {total} — copy the link below and send it to them yourself.',
  'users.showLink': 'Show the link for {email} anyway',
  'users.resent': 'Re-sent to {email}.',
  'users.resentLink': 'New link ready below — copy it. The old link no longer works.',
  'users.revokeConfirm': 'Revoke the invitation to {email}? Its link stops working.',
  'users.revoked': 'Invitation to {email} revoked — its link no longer works.',
  // Booth hosts who asked for access without an invitation (the /booth-access screen).
  'users.reqHeading': 'Booth access requests',
  'users.reqLead': 'People who asked to run a booth without an invitation. Nothing has changed on their account yet — approving is what grants it.',
  'users.reqWants': 'Asked for {booth}',
  'users.reqWantsNew': 'Asked for a new booth: {booth}',
  'users.reqOverride': '— put them on a different booth —',
  'users.reqHeldBy': 'Already run by {name} — approving adds a second person',
  'users.reqApprove': 'Approve',
  'users.reqReject': 'Reject',
  'users.reqApproved': 'Approved — they now run {booth}. Takes effect on their device within 15 minutes.',
  'users.reqRejected': 'Request rejected. Their account is unchanged.',
  'users.inviteHeading': 'Invite booth organizers',
  'users.inviteLead': 'The link signs them in on the booth device with their own account and opens their screen. Single-use, expires in 14 days or at the end of the event.',
  'users.name': 'Name',
  'users.email': 'Email',
  'users.role': 'Role',
  'users.booth': 'Booth',
  'users.boothPlaceholder': '— booth —',
  'users.bulkSummary': 'Bulk: paste',
  'users.bulkPerLine': 'per line',
  'users.inviteFilter': 'Invitation filter',
  'users.pending': 'Pending',
  'users.all': 'All',
  'users.thStatus': 'Status',
  'users.thSent': 'Sent',
  'users.resend': 'Resend',
  'users.revoke': 'Revoke',
  'users.noPending': 'No pending invitations.',
  'users.usersHeading': 'Users',
  'users.search': 'Search name, ID, passport, contact',
  'users.searchAria': 'Search users',
  'users.filterRole': 'Filter by role',
  'users.allRoles': 'All roles',
  'users.searchingAll': 'Searching all {count} users',
  'users.newestFirst': 'Newest first, 50 to a page',
  'users.showingPage': 'Showing {from}–{to}',
  'users.showingPageOf': 'Showing {from}–{to} of {total}',
  'users.page': 'Page {n}',
  'users.pages': 'Pages',
  'users.prev': 'Previous',
  'users.next': 'Next',
  'users.searching': 'Searching…',
  'users.searchFailed': 'The search could not be run — check the connection and try again',
  'users.searchCapped': 'only the newest {count} were searched',
  'users.pressRow': 'press a row to open it',
  'users.thAffiliation': 'Affiliation',
  'users.thCountry': 'Country',
  'users.thStamps': 'Stamps',
  'users.thPoints': 'Points',
  'users.thRegistered': 'Registered',
  'users.openRow': 'Open {name}',
  'users.nothingMatches': 'Nothing matches',
  'users.noUsers': 'No users yet',
  'users.inviteLinkFor': 'Invitation link for {email}',
  'users.erasureHeading': 'Erasure requests · {count}',
  'users.erasureLead': 'Erasing removes the account, passport, stamps and prize unlocks; booth counters stay. Dismiss a duplicate or test request with a reason — both actions are audited.',
  'users.unknownName': 'Unknown name',
  'users.requested': 'Requested {when}',
  'users.eraseNow': 'Erase now',
  'users.dismiss': 'Dismiss',
  'users.reasonAudit': 'Reason (kept in the audit log)',
  'users.reason': 'Reason',
  'users.cancel': 'Cancel',
  'users.eraseWarn': 'This removes the account, passport, stamps and prize unlocks. Booth counters stay. It cannot be undone.',
  'users.typeToConfirm': 'Type',
  'users.toConfirm': 'to confirm',
  'users.erasing': 'Erasing…',
  'users.erasePermanently': 'Erase permanently',
  'users.createHeading': 'Create a user at the desk',
  'users.contact': 'Email (or phone for a visitor)',
  'users.contactAria': 'Contact',
  'users.visitorType': 'Visitor type',
  'users.country': 'Country',
  'users.institution': 'Institution',
  'users.school': 'School (MFU)',
  'users.schoolAria': 'School',
  'users.studentId': 'Student ID (optional)',
  'users.studentIdAria': 'Student ID',
  'users.password': 'Password (optional · 10+ characters · needs an email contact)',
  'users.passwordAria': 'Password',
  'users.creating': 'Creating…',
  'users.createAccount': 'Create account',
  'users.noPasswordNote': 'Without a password the person signs in with Google on that address, or uses “Forgot your password?” to set one.',
  'users.editDetails': 'Edit details',
  'users.userId': 'User id',
  'users.type': 'Type',
  'users.days': 'Days',
  'users.lastSeen': 'Last seen',
  'users.pointsStamps': '{points} · {stamps} stamps',
  'users.ethnicNote': 'Ethnic group is never shown per person — it exists only as an aggregate on the dashboard.',
  'users.route': 'Route walked',
  'users.noStamps': 'No stamps yet',
  'users.apply': 'Apply',
  'users.remove': 'Remove',
  'users.softDelete': 'Delete (soft)',
  'users.erasePdpa': 'Erase permanently (PDPA)',
  'users.removeNote': 'Soft delete anonymises the contact and disables sign-in; stamps stay in the statistics. Erase is the right to be forgotten: everything about the person goes.',
  'users.prizes': 'Prizes',
  'users.void': 'Void',
  'users.voiding': 'Voiding…',
  'users.voided': '{tier} voided for {name} — the item is back in stock.',
  'users.contactEdit': 'Contact',
  'users.contactEditNote': '(an email here also becomes the sign-in address)',
  'users.mfuOnly': '(MFU only)',
  'users.saveChanges': 'Save changes',

  // ---------- users — send button ----------
  'users.sendInvitation': 'Send invitation',
  'users.sendInvitations': 'Send invitations',

  // ---------- prizes — row validation ----------
  'prizes.nPoints': '{n} points',
  'prizes.needsName': 'needs a name',
  'prizes.needsThreshold': 'needs a threshold of at least 1',
  'prizes.tooHigh': 'needs {points} points but only {available} are on the floor',

  // ---------- booth ratings (pages/admin/Ratings.tsx) ----------
  'admin.ratings.title': 'Booth ratings',
  'admin.ratings.lead': 'One to five stars, left by visitors right after they collect a stamp. Anonymous by design — a comment here cannot be traced to a person.',
  'admin.ratings.responses': 'Ratings left',
  'admin.ratings.average': 'Average, all booths',
  'admin.ratings.rated': 'Booths rated',
  'admin.ratings.byBooth': 'By booth',
  'admin.ratings.booth': 'Booth',
  'admin.ratings.filterBooth': 'Show comments for one booth',
  'admin.ratings.allBooths': 'All booths',
  'admin.ratings.avgShort': 'Average',
  'admin.ratings.n': 'Ratings',
  'admin.ratings.spread': 'Spread (1★ to 5★)',
  'admin.ratings.sort': 'Order',
  'admin.ratings.sort.best': 'Best rated first',
  'admin.ratings.sort.worst': 'Worst rated first',
  'admin.ratings.sort.most': 'Most rated first',
  'admin.ratings.sort.name': 'By name',
  'admin.ratings.comments': 'Comments',
  'admin.ratings.noComments': 'Nobody has written a comment yet.',
  'admin.ratings.capped': 'Showing the most recent {n}. Export the CSV above for the full counts.',

  // ---------- festival feedback survey (pages/admin/FestivalSurvey.tsx) ----------
  'admin.fsurvey.title': 'Festival feedback',
  'admin.fsurvey.lead': 'The one survey the festival itself asks, offered on the prize page. Answers carry no visitor id, so they can be read here in full.',
  'admin.fsurvey.state': 'Status',
  'admin.fsurvey.notInstalled': 'Not set up yet',
  'admin.fsurvey.live': 'Published — visitors can see it',
  'admin.fsurvey.draft': 'Saved, not published',
  'admin.fsurvey.counts': '{q} questions · {n} responses',
  'admin.fsurvey.install': 'Load the standard questions',
  'admin.fsurvey.reinstall': 'Reset to the standard questions',
  'admin.fsurvey.installHint': 'Load the questions first, check them, then publish. Nothing reaches a visitor until you publish.',
  'admin.fsurvey.installed': 'Questions saved. Publish when you are happy with them.',
  'admin.fsurvey.publish': 'Publish',
  'admin.fsurvey.unpublish': 'Unpublish',
  'admin.fsurvey.edited': 'These questions have been edited away from the standard set. That is fine — resetting would retire the current wording and start a new version.',
  'admin.fsurvey.editHint': 'To change the wording:',
  'admin.fsurvey.openBuilder': 'open the builder',
  'admin.fsurvey.results': 'Results · {n} responses',
  'admin.fsurvey.noneYet': 'Nobody has answered yet.',
  'admin.fsurvey.noAnswers': 'No answers to this one yet.',
} as const

export const adminTh: Record<keyof typeof adminEn, string> = {
  'label.zone.entrance': 'โซนทางเข้า',
  'label.zone.middle': 'โซนกลางฮอลล์',
  'label.zone.far': 'โซนด้านใน',
  'label.role.visitor': 'ผู้เข้าร่วม',
  'label.role.organizer': 'ผู้ดูแลบูธ',
  'label.role.admin': 'ผู้ดูแลระบบ',
  'label.visitorType.student': 'นักศึกษา',
  'label.visitorType.staff': 'บุคลากร',
  'label.visitorType.alumni': 'ศิษย์เก่า',
  'label.visitorType.guest': 'ผู้มาเยี่ยม',

  'admin.title': 'ระบบผู้ดูแลพาสปอร์ต',
  'admin.rail.brand': 'ผู้ดูแลระบบ',
  'admin.menu': 'เมนู',
  'admin.rail.expand': 'ขยายแถบเมนู',
  'admin.rail.collapse': 'ย่อแถบเมนู',
  'admin.group.run': 'ระหว่างงาน',
  'admin.group.setup': 'ตั้งค่า',
  'admin.group.records': 'บันทึก',
  'admin.group.screens': 'หน้าจอ',
  'admin.nav.dashboard': 'ภาพรวม',
  'admin.nav.draw': 'จับรางวัลบนเวที',
  'admin.nav.event': 'งานอีเวนต์',
  'admin.nav.booths': 'บูธ',
  'admin.nav.prizes': 'ของรางวัลและสต็อก',
  'admin.nav.users': 'ผู้ใช้และคำเชิญ',
  'admin.nav.audit': 'บันทึกการใช้งาน',
  'admin.nav.refdata': 'รายการอ้างอิง',
  'admin.nav.ratings': 'คะแนนซุ้ม',
  'admin.nav.feedback': 'แบบประเมินงาน',
  'admin.nav.wall': 'จอในฮอลล์',
  'admin.nav.desk': 'จุดแลกของรางวัล',

  // first-admin setup (Setup)
  'setup.title': 'ตั้งค่าผู้ดูแลระบบคนแรก',
  'setup.signedInAs': 'เข้าสู่ระบบด้วย',
  'setup.becomesAdmin': '— บัญชีนี้จะกลายเป็นผู้ดูแลระบบ',
  'setup.keyBefore': 'กรอกคีย์เริ่มต้นระบบที่ตั้งไว้ด้วยคำสั่ง',
  'setup.keyAfter': 'ใช้ได้ครั้งเดียว เฉพาะเมื่อยังไม่มีผู้ดูแลระบบ หลังจากนั้นเพิ่มผู้ดูแลระบบได้จากหน้าผู้ดูแล',
  'setup.already': 'บัญชีนี้เป็นผู้ดูแลระบบอยู่แล้ว',
  'setup.yourName': 'ชื่อของคุณ',
  'setup.key': 'คีย์เริ่มต้นระบบ',
  'setup.submit': 'ตั้งให้ฉันเป็นผู้ดูแลระบบ',

  // printable booth cards (BoothCards)
  'boothCards.hint': 'การ์ด {count} ใบ หน้าละหนึ่งใบ พิมพ์บนกระดาษ A4 หรือเลือก “บันทึกเป็น PDF”',
  'boothCards.hintOne': 'การ์ดหนึ่งใบ พิมพ์บนกระดาษ A4 หรือเลือก “บันทึกเป็น PDF”',
  'boothCards.printAll': 'พิมพ์ทั้งหมด',
  'boothCards.back': 'ย้อนกลับ',
  'boothCards.none': 'ยังไม่มีบูธที่เปิดใช้งาน',

  // go-live checklist (Readiness)
  'readiness.title': 'พร้อมจัดงานหรือยัง',
  'readiness.of': '{done} จาก {total}',
  'readiness.starts': 'เริ่ม {when}',
  'readiness.hide': 'ซ่อน',
  'readiness.booths': 'มีบูธที่เปิดใช้งานอย่างน้อยหนึ่งบูธ',
  'readiness.boothsDetail': 'เปิดใช้งาน {count} บูธ',
  'readiness.prizes': 'บันทึกเกณฑ์ของรางวัลแล้ว',
  'readiness.prizesDetail': '{count} ระดับ',
  'readiness.organizers': 'บูธที่เปิดใช้งานทุกบูธมีผู้ดูแลแล้ว',
  'readiness.organizersDetail': 'ยังไม่มี {count} บูธ: {names}',
  'readiness.signIn': 'บัญชีผู้ดูแลของคุณเข้าสู่ระบบจากเครื่องอื่นได้',
  'readiness.signInDetail': 'มีรหัสผ่านหรือ Google',
  'readiness.mail': 'อีเมลคำเชิญ',
  'readiness.mailOk': 'ตั้งค่าอีเมลคำเชิญแล้ว',
  'readiness.mailNo': 'ยังไม่ได้ตั้งค่าอีเมลคำเชิญ',
  'readiness.mailChecking': 'กำลังตรวจสอบ…',
  'readiness.mailDetail': 'คำเชิญจะแสดงลิงก์ให้คัดลอกแทน ซึ่งเพียงพอสำหรับทีมขนาดเล็ก',

  // audit log (Audit)
  'audit.title': 'บันทึกการใช้งาน',
  'audit.lead': 'ทุกการดำเนินการของผู้ดูแล เรียงจากใหม่สุด แสดง {shown} รายการ',
  'audit.ofTotal': '{shown} จาก {total}',
  'audit.filterAction': 'กรองตามการดำเนินการ',
  'audit.allActions': 'ทุกการดำเนินการ',
  'audit.search': 'ค้นหาเป้าหมายหรือผู้ดำเนินการ…',
  'audit.searchLabel': 'ค้นหา',
  'audit.csv': 'CSV (มีข้อมูลส่วนบุคคล)',
  'audit.csvConfirm': 'ไฟล์นี้มีค่าก่อนและหลังการแก้ไขข้อมูลผู้ใช้ ซึ่งรวมข้อมูลติดต่อ ต้องการดำเนินการต่อหรือไม่',
  'audit.when': 'เวลา',
  'audit.action': 'การดำเนินการ',
  'audit.target': 'เป้าหมาย',
  'audit.actor': 'ผู้ดำเนินการ',
  'audit.change': 'การเปลี่ยนแปลง',
  'audit.diff': 'ดูรายละเอียด',
  'audit.noMatch': 'ไม่พบรายการที่ตรงกัน',
  'audit.none': 'ยังไม่มีรายการ',
  'audit.loadMore': 'โหลดเพิ่ม {count} รายการ',

  // stage draw (Draw)
  'draw.title': 'จับรางวัลบนเวที',
  'draw.lead': 'สุ่มจากผู้เข้าร่วมที่ได้รับระดับรางวัลซึ่งให้สิทธิ์ร่วมจับรางวัล ผู้ที่ถูกจับไปแล้วจะไม่ถูกนำมาสุ่มซ้ำ และทุกครั้งจะถูกบันทึกไว้',
  'draw.noTierBefore': 'ยังไม่มีระดับรางวัลใดให้สิทธิ์ร่วมจับรางวัล จึงยังไม่มีผู้เข้าร่วมให้สุ่ม ให้ติ๊ก',
  'draw.noTierTick': 'สิทธิ์ร่วมจับรางวัลบนเวที',
  'draw.noTierAfter': 'ที่ระดับรางวัลในหน้าของรางวัลและสต็อก',
  'draw.inHat': 'อยู่ในการสุ่ม',
  'draw.alreadyDrawn': 'ถูกจับไปแล้ว ไม่นำมาสุ่มซ้ำ',
  'draw.grantsEntry': 'ให้สิทธิ์ร่วมจับรางวัล',
  'draw.winners': 'จำนวนผู้ได้รับรางวัล',
  'draw.drawing': 'กำลังสุ่ม…',
  'draw.draw': 'สุ่มรางวัล',
  'draw.confirm': 'สุ่มผู้ได้รับรางวัลเพิ่ม {count} คนหรือไม่ ผู้ที่ถูกจับไปแล้วจะไม่ถูกนำมาสุ่มซ้ำ และจะบันทึกเป็นการจับรางวัลครั้งใหม่',
  'draw.revealBefore': 'การประกาศผลจะแสดงบน',
  'draw.revealLink': 'จอในฮอลล์ ↗',
  'draw.revealAfter': ' โดยจะแทนสถิติสดประมาณหนึ่งนาที แล้วกลับไปแสดงสถิติตามเดิม',
  'draw.range': 'เลือกจำนวนผู้ได้รับรางวัลระหว่าง 1 ถึง 20 คน',
  'draw.noneEligible': 'ขณะนี้ยังไม่มีผู้มีสิทธิ์',
  'draw.allDrawn': 'ผู้มีสิทธิ์ทั้งหมดถูกจับไปแล้ว',
  'draw.noneQualified': 'ยังไม่มีผู้เข้าร่วมคนใดถึงระดับที่ให้สิทธิ์ร่วมจับรางวัล',
  'draw.onScreenNow': 'กำลังแสดงบนจอในฮอลล์',
  'draw.foundNobody': 'การจับรางวัลครั้งนั้นไม่พบผู้มีสิทธิ์',
  'draw.drawnFrom': 'สุ่มจากผู้มีสิทธิ์ {count} คน เมื่อ {when}',
  'draw.everyDraw': 'การจับรางวัลทั้งหมด',
  'draw.thWinner': 'ผู้ได้รับรางวัล',
  'draw.thPassport': 'เลขพาสปอร์ต',
  'draw.thPool': 'จำนวนผู้มีสิทธิ์',

  // reference lists (RefData)
  'refData.title': 'รายการอ้างอิง',
  'refData.lead': 'ตัวเลือกที่แสดงในแบบฟอร์มลงทะเบียน แก้ไขได้ที่นี่ จึงเปลี่ยนระหว่างงานได้โดยไม่ต้องดีพลอยใหม่ — เดิมแก้ได้ด้วยการรันสคริปต์ seed เท่านั้น',
  'refData.tab.institutions': 'สถาบัน',
  'refData.tab.schools': 'สำนักวิชา มฟล.',
  'refData.tab.ethnic': 'กลุ่มชาติพันธุ์',
  'refData.blurb.institutions': 'มหาวิทยาลัยที่แสดงในแบบฟอร์มลงทะเบียน ผู้เข้าร่วมยังพิมพ์ชื่ออื่นได้ รายการนี้เป็นเพียงตัวเลือกแนะนำ',
  'refData.blurb.schools': 'แสดงเมื่อผู้เข้าร่วมเลือก มฟล. เป็นสถาบันของตน',
  'refData.blurb.ethnic': 'แยกตามประเทศต้นทาง เป็นข้อมูลอ่อนไหวตาม พ.ร.บ.คุ้มครองข้อมูลส่วนบุคคล มาตรา 26 ผู้เข้าร่วมเลือกตอบหรือไม่ก็ได้ ต้องให้ความยินยอมแยก ไม่แสดงรายบุคคล และซ่อนกลุ่มที่ต่ำกว่า 5 คนในภาพรวม ข้อความส่วนนี้อยู่ในความดูแลของส่วนความสัมพันธ์ระหว่างประเทศ',
  'refData.discard': 'ละทิ้งการแก้ไขที่ยังไม่บันทึกในรายการนี้หรือไม่',
  'refData.savedCountries': 'บันทึก {count} ประเทศแล้ว แบบฟอร์มลงทะเบียนจะใช้ค่านี้ทันที',
  'refData.savedEntries': 'บันทึก {count} รายการแล้ว แบบฟอร์มลงทะเบียนจะใช้ค่านี้ทันที',
  'refData.removeCountry': 'ลบประเทศ',
  'refData.addCountry': 'เพิ่มประเทศ (รหัส ISO)',
  'refData.add': 'เพิ่ม',
  'refData.onePerLine': 'บรรทัดละหนึ่งรายการ · {count} รายการ',
  'refData.sortNote': 'บันทึกโดยเรียงตามตัวอักษร ตัดรายการซ้ำและบรรทัดว่างออก',
  'refData.keepOther': 'คงตัวเลือก "อื่น ๆ" ไว้ในรายการ เพราะแบบฟอร์มจะแสดงช่องพิมพ์อิสระเมื่อเลือกตัวเลือกนี้',
  'common.save': 'บันทึก',
  'common.discardChanges': 'ละทิ้งการแก้ไข',

  // printable report (Print)
  'print.hint': 'ในหน้าต่างสั่งพิมพ์ ให้เลือก “บันทึกเป็น PDF” สำหรับรายงาน ไม่จำเป็นต้องใช้แนวนอน',
  'print.print': 'พิมพ์ / บันทึกเป็น PDF',
  'print.back': 'ย้อนกลับ',
  'print.title': 'ภาพรวมพาสปอร์ต',
  'print.allDays': 'ทุกวัน',
  'print.day': 'วันที่ {n}',
  'print.generated': 'สร้างเมื่อ {when}',
  'print.countersLive': 'ตัวนับเป็นข้อมูลสด',
  'print.countersAge': 'ตัวนับเก่า {min} นาที',
  'print.visitors': 'ผู้ลงทะเบียน',
  'print.stamps': 'ตราที่เก็บได้',
  'print.redeemed': 'ของรางวัลที่แลกแล้ว',
  'print.active15': 'ใช้งานใน 15 นาทีที่ผ่านมา',
  'print.leaderboard': 'อันดับบูธ',
  'print.noBooths': 'ไม่มีบูธ',
  'print.perFive': 'ตราต่อ 5 นาที',
  'print.noScans': 'ยังไม่มีการสแกน',
  'print.countries': 'ประเทศ · {count} ประเทศ',
  'print.noRegistrations': 'ยังไม่มีผู้ลงทะเบียน',
  'print.participation': 'การเข้าร่วม',
  'print.thai': 'ไทย',
  'print.international': 'ต่างชาติ',
  'print.funnelTitle': 'ลำดับขั้นผู้เข้าร่วม',
  'print.institutions': 'สถาบัน',
  'print.schools': 'สำนักวิชา มฟล.',
  'print.stock': 'สต็อกของรางวัล',
  'print.cross': 'ข้ามสำนักวิชา · สำนักวิชาของผู้เข้าร่วม × บูธ',
  'print.school': 'สำนักวิชา',
  'print.ethnic': 'กลุ่มชาติพันธุ์ · ภาพรวม · ตอบ {rate}%',
  'print.footer': 'แสดงเฉพาะภาพรวม ไม่มีข้อมูลส่วนบุคคล กลุ่มชาติพันธุ์ที่ต่ำกว่า 5 คนจะรวมเป็น “อื่น ๆ” และจะไม่แสดงส่วนนี้เลยหากผู้ให้ความยินยอมน้อยกว่า 20 คน',
  'print.nothingYet': 'ยังไม่มีข้อมูล',
  'funnel.registered': 'ลงทะเบียนแล้ว',
  'funnel.oneStamp': 'มีตราตั้งแต่ 1 ดวง',
  'funnel.tierReached': 'ถึงระดับรางวัล',
  'funnel.redeemed': 'แลกของรางวัลแล้ว',

  // hall screen (Wall)
  'wall.title': 'พาสปอร์ตสด',
  'wall.adminConsole': 'หน้าผู้ดูแลระบบ',
  'wall.drawing': 'กำลังสุ่ม',
  'wall.winner': 'ผู้ได้รับรางวัล',
  'wall.winners': 'ผู้ได้รับรางวัล',
  'wall.nobodyEligible': 'ไม่มีผู้มีสิทธิ์',
  'wall.visitors': 'ผู้เข้าร่วม',
  'wall.stamps': 'ตรา',
  'wall.prizes': 'ของรางวัล',
  'wall.joinHere': 'เริ่มสร้างพาสปอร์ต',
  'wall.step1': 'สแกน QR',
  'wall.step2': 'สะสมตราประทับจากทุกซุ้ม',
  'wall.step3': 'นำคะแนนไปแลกของรางวัล',
  'wall.busiest': 'ซุ้มที่มีผู้เข้าร่วมมากที่สุดตอนนี้',
  'wall.drawnFrom': 'สุ่มจากผู้มีสิทธิ์ {n} คน',
  'wall.pressF': 'กด F เพื่อเข้าโหมดเต็มหน้าจอ',
  'wall.fsIos': 'iPhone และ iPad ไม่สามารถเข้าโหมดเต็มหน้าจอจากใน Safari ได้ ให้กดปุ่มแชร์ เลือก “เพิ่มไปยังหน้าจอโฮม” แล้วเปิดจอในฮอลล์จากไอคอนนั้น',

  // live dashboard (Dashboard)
  'dash.title': 'ภาพรวม',
  'dash.live': 'สด',
  'dash.connected': 'เชื่อมต่อแล้ว',
  'dash.reconnecting': 'กำลังเชื่อมต่อใหม่',
  'dash.countersAge': 'ตัวนับเก่า {min} นาที',
  'dash.daySelector': 'เลือกวัน',
  'dash.allDays': 'ทุกวัน',
  'dash.printPdf': 'พิมพ์ / PDF',
  'dash.leaderboard': 'อันดับบูธ',
  'dash.topBooth': '★ บูธอันดับหนึ่ง',
  'dash.needsTraffic': 'ยังมีผู้เข้าน้อย',
  'dash.countries': 'ประเทศ · {count} ประเทศ',
  'dash.institutions': 'สถาบัน · สำนักวิชา มฟล.',
  'dash.cross': 'ข้ามสำนักวิชา · ใครไปบูธของใคร',
  'dash.manage': 'จัดการ',
  'dash.ethnic': 'กลุ่มชาติพันธุ์ · ภาพรวมเท่านั้น',
  'dash.ethnicConfirm': 'ไฟล์นี้มีจำนวนกลุ่มชาติพันธุ์ในภาพรวม (กลุ่มที่ต่ำกว่า 5 คนรวมเป็นอื่น ๆ แล้ว) เป็นข้อมูลอ่อนไหวตาม พ.ร.บ.คุ้มครองข้อมูลส่วนบุคคล มาตรา 26 — ต้องการดำเนินการต่อหรือไม่',
  'dash.ethnicHidden': 'จะแสดงเมื่อมีผู้ให้ความยินยอมอย่างน้อย 20 คน (ขณะนี้ {count} คน) กลุ่มที่ต่ำกว่า 5 คนจะรวมเป็น "อื่น ๆ"',
  'dash.ethnicRate': 'อัตราการตอบ {rate}% · กลุ่มที่ต่ำกว่า 5 คนรวมเป็นอื่น ๆ',
  'dash.crossEmpty': 'จะแสดงเมื่อผู้เข้าร่วมเริ่มสแกน',
  'dash.crossHeader': 'สำนักวิชาของผู้เข้าร่วม ↓ · บูธ →',
  'dash.crossNote': 'วงสีทอง = บูธของสำนักวิชานั้นเอง ช่องอื่นในแถวที่มีตัวเลขหมายถึงผู้เข้าร่วมออกไปเยี่ยมบูธอื่น',

  // prizes and stock (Prizes)
  'prizes.title': 'ของรางวัลและสต็อก',
  'prizes.counting': 'กำลังรวมคะแนนพื้นฐาน…',
  'prizes.floor': 'มีคะแนนพื้นฐานรวม {points} คะแนน จากบูธที่เปิดใช้งาน {booths} บูธ เกณฑ์ที่สูงกว่านี้จะถูกปฏิเสธ และเกณฑ์ที่ห่างไม่ถึง 10 คะแนนจะถูกเตือน การปรับคะแนนชั่วคราวของบูธไม่เปลี่ยนเกณฑ์นี้',
  'prizes.saved': 'บันทึกเกณฑ์แล้ว การลดเกณฑ์จะปลดล็อกทันที การเพิ่มเกณฑ์ไม่ยกเลิกสิทธิ์ที่ได้ไปแล้ว',
  'prizes.previewOnly': 'แสดงตัวอย่างเท่านั้น ยังไม่บันทึก ผลที่จะเกิดขึ้นแสดงอยู่ใต้แต่ละระดับ',
  'prizes.remoteChanged': 'ผู้ดูแลอีกคนแก้ไขเกณฑ์ของรางวัลระหว่างที่คุณกำลังแก้อยู่',
  'prizes.discardMine': 'ละทิ้งการแก้ไขของฉัน',
  'prizes.thenLoad': 'เพื่อโหลดของเขา หรือกดบันทึกเพื่อเขียนทับ',
  'prizes.tiers': 'ระดับรางวัล',
  'prizes.unsaved': 'มีการแก้ไขที่ยังไม่บันทึก',
  'prizes.newTier': 'ระดับใหม่',
  'prizes.drawEntry': 'สิทธิ์จับรางวัล',
  'prizes.ofLeft': 'เหลือจาก {total}',
  'prizes.name': 'ชื่อ',
  'prizes.namePlaceholder': 'นักสำรวจ',
  'prizes.unlocksAt': 'ปลดล็อกเมื่อถึง',
  'prizes.points': 'คะแนน',
  'prizes.reward': 'ของรางวัล',
  'prizes.rewardPlaceholder': 'กระเป๋าผ้า',
  'prizes.initialStock': 'จำนวนตั้งต้น',
  'prizes.stageDrawEntry': 'ให้สิทธิ์ร่วมจับรางวัลบนเวที',
  'prizes.addNote': 'เพิ่มข้อความเมื่อของหมด',
  'prizes.noteLabel': 'ข้อความที่แสดงต่อผู้เข้าร่วมเมื่อของหมด',
  'prizes.notePlaceholder': 'เช่น รับได้ที่จุดประชาสัมพันธ์หลัง 15:00',
  'prizes.thisTier': 'ระดับนี้',
  'prizes.remove': 'ลบ',
  'prizes.removeOnSave': 'ลบเมื่อบันทึก',
  'prizes.willDeactivateOne': '{names} จะถูกปิดใช้งานเมื่อบันทึก ผู้เข้าร่วมที่ปลดล็อกไปแล้วยังคงสิทธิ์เดิม',
  'prizes.willDeactivateMany': '{names} จะถูกปิดใช้งานเมื่อบันทึก ผู้เข้าร่วมที่ปลดล็อกไปแล้วยังคงสิทธิ์เดิม',
  'prizes.addTier': 'เพิ่มระดับรางวัล',
  'prizes.checking': 'กำลังตรวจสอบ…',
  'prizes.previewEffect': 'ดูผลก่อนบันทึก',
  'prizes.adjust': 'ปรับสต็อก',
  'prizes.adjustLead': 'จำนวนจะไม่ถูกพิมพ์ทับ ทุกการเปลี่ยนแปลงเป็นรายการปรับที่มีเหตุผลกำกับ ตัวเลขปิดงานจึงกระทบยอดกับจำนวนที่รับเข้าได้',
  'prizes.tier': 'ระดับรางวัล',
  'prizes.tierPlaceholder': '— เลือกระดับ —',
  'prizes.kind': 'ประเภท',
  'prizes.restock': 'รับเข้าเพิ่ม (+)',
  'prizes.correction': 'แก้ไขจำนวน (±)',
  'prizes.delta': 'จำนวนที่เปลี่ยน (จำนวนเต็ม เช่น 50 หรือ -3)',
  'prizes.reasonLedger': 'เหตุผล (บันทึกไว้ในทะเบียน)',
  'prizes.applying': 'กำลังบันทึก…',
  'prizes.apply': 'บันทึกการปรับ',
  'prizes.adjusted': 'ปรับสต็อก {delta} และบันทึกไว้แล้ว',
  'prizes.perSession': 'รอบละ {n}',
  'prizes.allowance': 'จำนวนต่อรอบ',
  'prizes.allowanceLead': 'จำนวนของรางวัลที่แต่ละรอบเริ่มต้น มีผลกับทุกรอบที่ยังไม่มีการรับของ รอบที่กำลังดำเนินอยู่จะคงจำนวนเดิมไว้ รวมถึงรอบที่เปิดอยู่ขณะนี้ หากต้องการเพิ่มของรางวัลในรอบที่เปิดอยู่ ให้ใช้การปรับสต็อกด้านบน',
  'prizes.allowanceField': 'ของรางวัลต่อรอบ',
  'prizes.allowanceApply': 'บันทึกจำนวนต่อรอบ',
  'prizes.allowanceSetting': 'กำลังบันทึก…',
  'prizes.allowanceSet': 'เปลี่ยนจำนวนต่อรอบจาก {from} เป็น {to} และบันทึกไว้แล้ว',
  'prizes.recent': 'การปรับล่าสุด',
  'prizes.noAdjustments': 'ยังไม่มีการปรับ สต็อกยังเป็นจำนวนที่ตั้งต้นไว้',
  'prizes.void': 'ยกเลิกการแลกของรางวัล',
  'prizes.voidLeadBefore': 'คืนของเข้าสต็อกและให้ผู้เข้าร่วมคนนั้นรับได้อีกครั้ง ทำได้ง่ายกว่าที่หน้า',
  'prizes.voidLeadAfter': ' โดยเปิดข้อมูลผู้เข้าร่วมแล้วกด',
  'prizes.voidLeadEnd': 'ข้างของรางวัล แบบฟอร์มนี้ต้องใช้รหัสผู้ใช้ที่แสดงอยู่ที่นั่น',
  'prizes.userId': 'รหัสผู้ใช้',
  'prizes.reasonAudit': 'เหตุผล (บันทึกไว้ในบันทึกการใช้งาน)',
  'prizes.voiding': 'กำลังยกเลิก…',
  'prizes.voidBtn': 'ยกเลิกการแลก…',
  'prizes.voidConfirm': 'ยกเลิก {tier} ของผู้เข้าร่วม {uid} หรือไม่ ของจะกลับเข้าสต็อกและผู้เข้าร่วมรับได้อีกครั้ง',
  'prizes.voidThisTier': 'ระดับนี้',
  'prizes.voided': 'ยกเลิกการแลกแล้ว ของกลับเข้าสต็อก',
  'prizes.users': 'ผู้ใช้',
  'prizes.voidWord': 'ยกเลิก',

  // prizes — inline hints
  'prizes.within10': 'ห่างจากคะแนนรวม {points} ไม่ถึง 10 คะแนน',
  'prizes.unlocksFor': 'จะปลดล็อกให้ผู้เข้าร่วม {count} คน',

  // booths (Booths)
  'booths.title': 'บูธ',
  'booths.printAll': 'พิมพ์การ์ดทั้งหมด',
  'booths.new': 'เพิ่มบูธ',
  'booths.editTitle': 'แก้ไข · {name}',
  'booths.nameEn': 'ชื่อ (อังกฤษ)',
  'booths.nameTh': 'ชื่อ (ไทย ไม่บังคับ)',
  'booths.shortName': 'ชื่อย่อบนตรา',
  'booths.hostUnit': 'หน่วยงานเจ้าของบูธ',
  'booths.location': 'ตำแหน่งที่ตั้ง',
  'booths.zone': 'โซน',
  'booths.order': 'ลำดับในตาราง',
  'booths.orderPlaceholder': 'ลำดับถัดไป',
  'booths.accent': 'สีประจำบูธ',
  'booths.accentAria': 'สีประจำบูธ {colour}',
  'booths.stampPreview': 'ตัวอย่างตรา',
  'booths.description': 'คำอธิบาย',
  'booths.presentOn': 'เปิดให้บริการวัน',
  'booths.isPrizeDesk': 'บูธนี้เป็นจุดแลกของรางวัล',
  'booths.active': 'เปิดใช้งาน',
  'booths.create': 'สร้างบูธ',
  'booths.cancel': 'ยกเลิก',
  'booths.filter': 'กรองตามชื่อ หน่วยงาน ตำแหน่ง หรือโซน',
  'booths.filterAria': 'กรองบูธ',
  'booths.unstaffedOnly': 'เฉพาะบูธที่ยังไม่มีผู้ดูแล',
  'booths.shownOf': '{shown} จาก {total}',
  'booths.none': 'ยังไม่มีบูธ กด “เพิ่มบูธ”',
  'booths.noMatch': 'ไม่พบบูธที่ตรงกัน',
  'booths.days': '{done}/{total} วัน',
  'booths.prizeDesk': 'จุดแลกของรางวัล',
  'booths.inactive': 'ปิดใช้งาน',
  'booths.keep': 'เก็บไว้ใช้กับงานนี้',
  'booths.delete': 'ลบ',
  'booths.edit': 'แก้ไข',
  'booths.openScreen': 'เปิดหน้าจอบูธ',
  'booths.stats': 'สถิติ',
  'booths.moreActions': 'การทำงานเพิ่มเติมของ {name}',
  'booths.more': 'เพิ่มเติม ▾',
  'booths.replaceBadge': 'เปลี่ยนรูปตรา…',
  'booths.uploadBadge': 'อัปโหลดรูปตรา…',
  'booths.removeBadge': 'ลบรูปตรา',
  'booths.replacePhoto': 'เปลี่ยนรูปภาพ…',
  'booths.uploadPhoto': 'อัปโหลดรูปภาพ…',
  'booths.removePhoto': 'ลบรูปภาพ',
  'booths.rotateSecret': 'เปลี่ยนรหัสลับ…',
  'booths.deleteBooth': 'ลบบูธ…',
  'booths.rotateConfirm': 'เปลี่ยนรหัสลับของ {name} หรือไม่ รหัสที่แสดงอยู่บนหน้าจอหรือในภาพถ่ายจะใช้ไม่ได้ทันที',
  'booths.deleteConfirm': 'ลบ {name} หรือไม่ หากมีการเก็บตราไปแล้ว ระบบจะปิดใช้งานแทนการลบ',
  'booths.badgeTooBig': 'รูปตราต้องมีขนาดไม่เกิน 512 KB',
  'booths.photoTooBig': 'รูปภาพต้องมีขนาดไม่เกิน 2 MB',
  'booths.removeBadgeConfirm': 'ลบรูปตราของ {name} หรือไม่ ระบบจะใช้ตราที่สร้างอัตโนมัติแทน',
  'booths.removePhotoConfirm': 'ลบรูปภาพของ {name} หรือไม่',
  'booths.bulk': 'นำเข้าหลายบูธ: วางรายการบูธ',
  'booths.bulkLine': 'บรรทัดละหนึ่งบูธ:',
  'booths.bulkCols': ' และคอลัมน์ที่ห้าสำหรับคะแนน (ไม่บังคับ)',
  'booths.bulkZone': 'โซนคือ',
  'booths.bulkZoneAfter': '(ค่าเริ่มต้น {entrance} / {middle} / {far} คะแนน) รูปตรา วันที่ และการตั้งเป็นจุดแลกของรางวัล ตั้งได้ที่การ์ดบูธภายหลัง',
  'booths.bulkAria': 'รายการบูธ',
  'booths.bulkBad': '{count} บรรทัดต้องมีชื่อและโซนเป็น entrance / middle / far: {lines}',
  'booths.bulkCreate': 'สร้าง {count} บูธ',
  'booths.bulkProgress': 'กำลังสร้าง {n} จาก {total}…',
  'booths.bulkFailed': 'สร้างสำเร็จ {made} ล้มเหลว {failed} — {detail}',
  'booths.bulkDone': 'สร้างบูธแล้ว {count} บูธ',
  'booths.organizer': 'ผู้ดูแลบูธ',
  'booths.invited': 'เชิญแล้ว',
  'booths.resend': 'ส่งใหม่',
  'booths.organizerName': 'ชื่อผู้ดูแลบูธ',
  'booths.organizerEmail': 'อีเมลผู้ดูแลบูธ',
  'booths.name': 'ชื่อ',
  'booths.email': 'อีเมล',
  'booths.sending': 'กำลังส่ง…',
  'booths.send': 'ส่ง',
  'booths.noOrganizer': 'ยังไม่มีผู้ดูแลบูธ',
  'booths.inviteOrganizer': 'เชิญผู้ดูแลบูธ',
  'booths.inviteLink': 'ลิงก์คำเชิญ',
  'booths.showLink': 'แสดงลิงก์',
  'booths.mailed': 'ส่งคำเชิญไปยัง {email} แล้ว',
  'booths.mailOff': 'ยังไม่ได้ตั้งค่าอีเมล ให้คัดลอกลิงก์ใต้ {name} แล้วส่งเอง',
  'booths.resent': 'ส่งใหม่ไปยัง {email} แล้ว',
  'booths.resentLink': 'ลิงก์ใหม่พร้อมแล้วใต้ {name} ให้คัดลอกไปใช้ ลิงก์เดิมจะใช้ไม่ได้อีก',

  // event lifecycle (Event)
  'event.title': 'งานอีเวนต์',
  'event.loading': 'กำลังโหลดรายการงาน…',
  'event.current': 'งานปัจจุบัน',
  'event.draft': 'ฉบับร่าง · {id}',
  'event.newEvent': 'งานใหม่ (เริ่มเป็นฉบับร่าง)',
  'event.backToCurrent': 'กลับไปที่งานปัจจุบัน',
  'event.nameEn': 'ชื่อ (อังกฤษ)',
  'event.nameTh': 'ชื่อ (ไทย ไม่บังคับ)',
  'event.starts': 'เริ่ม',
  'event.ends': 'สิ้นสุด',
  'event.days': 'วันที่จัดงาน',
  'event.dayN': 'วันที่ {n}',
  'event.qrPeriod': 'รอบเปลี่ยน QR (วินาที)',
  'event.qrRange': '10 ถึง 120 วินาที',
  'event.prefix': 'คำนำหน้าเลขพาสปอร์ต',
  'event.prefixHint': 'เลขจะเป็น {prefix}-0001',
  'event.zonePoints': 'คะแนนเริ่มต้นต่อโซน',
  'event.zoneNote': 'มีผลกับบูธที่สร้างหลังจากนี้ บูธเดิมยังใช้คะแนนเดิม และคะแนนที่ให้ไปแล้วจะคงไว้ตามเวลาที่สแกน',
  'event.prizeSessions': 'ช่วงเวลารับของรางวัล',
  'event.prizeSessionsNote': 'แต่ละช่วงเวลามีจำนวนของรางวัลของตัวเอง ช่วงเวลาจำกัดเฉพาะการรับของรางวัล ไม่ใช่คะแนน ผู้เข้าชมที่สะสมครบขณะจุดแจกปิดอยู่จะเก็บคะแนนไว้ทั้งหมดและมารับในช่วงถัดไปได้ หากจำเป็นต้องแจกนอกช่วงเวลา ให้ขยายช่วงเวลาที่นี่',
  'event.sessionLabel': 'ชื่อช่วงเวลา',
  'event.sessionFrom': 'ตั้งแต่',
  'event.sessionTo': 'ถึง',
  'event.addSession': 'เพิ่มช่วงเวลา',
  'event.removeSession': 'ลบ',
  'event.sessionOverlap': 'ช่วงเวลาต้องไม่ซ้อนทับกัน และเวลาสิ้นสุดต้องอยู่หลังเวลาเริ่ม',
  'event.createDraft': 'สร้างฉบับร่าง',
  'event.unsaved': 'มีการแก้ไขที่ยังไม่บันทึก',
  'event.goLive': 'เปิดใช้งานจริง',
  'event.saved': 'บันทึกงานแล้ว',
  'event.created': 'สร้าง "{id}" เป็นฉบับร่างแล้ว เพิ่มบูธและเกณฑ์ของรางวัล จากนั้นกดเปิดใช้งานจริง',
  'event.nowLive': 'งานนี้เปิดใช้งานจริงแล้ว',
  'event.deleteDraftConfirm': 'ลบฉบับร่าง "{name}" หรือไม่ การกระทำนี้ย้อนกลับไม่ได้',
  'event.draftDeleted': 'ลบฉบับร่าง "{id}" แล้ว',
  'event.after': 'หลังจบงาน · จัดเก็บงานนี้ แล้วเตรียมงานถัดไป',
  'event.afterLead': 'บูธ ของรางวัล และบัญชีผู้ใช้ ใช้ร่วมกันทุกงาน ไม่ได้คัดลอกแยกต่อหนึ่งงาน วิธีเปลี่ยนงานคือจัดเก็บงานปัจจุบัน (ตัวเลขรวมจะถูกตรึงไว้) ซึ่งจะล้างตราและความคืบหน้า แล้วจึงเปิดใช้งานงานถัดไป เตรียมฉบับร่างล่วงหน้าได้ แต่เฉพาะการตั้งค่าของงานนั้น บูธและของรางวัลจะคงเดิมจนกว่าจะจัดเก็บ',
  'event.newDraft': 'สร้างงานฉบับร่างใหม่',
  'event.all': 'งานทั้งหมด',
  'event.edit': 'แก้ไข',
  'event.deleteDraft': 'ลบฉบับร่าง',
  'event.danger': 'พื้นที่อันตราย',
  'event.dangerBefore': 'จัดเก็บ',
  'event.dangerAfter': 'แล้วเริ่มงานใหม่ ตัวเลขรวมจะถูกตรึงไว้ในคลังข้อมูลแบบอ่านอย่างเดียวก่อน จากนั้นตรา สิทธิ์ของรางวัล ตัวนับ และความคืบหน้าของผู้เข้าร่วมจะถูกล้าง เพื่อให้งานถัดไปเริ่มจากศูนย์ การกระทำนี้ย้อนกลับไม่ได้',
  'event.archiveStart': 'จัดเก็บและเริ่มงานใหม่',
  'event.keepBooths': 'เก็บบูธไว้ (ตัวนับกลับเป็นศูนย์ และรหัสลับ QR ทุกบูธจะถูกเปลี่ยนใหม่)',
  'event.keepTiers': 'เก็บเกณฑ์ของรางวัลไว้ (สต็อกจะกลับไปเท่าจำนวนที่รับเข้าเต็มจำนวน)',
  'event.hardDelete': 'ลบบัญชีผู้เข้าร่วมทิ้งด้วย (ตาม พ.ร.บ.คุ้มครองข้อมูลส่วนบุคคล) มิฉะนั้นจะล้างเฉพาะความคืบหน้าและเก็บบัญชีไว้',
  'event.typeToConfirm': 'พิมพ์',
  'event.toConfirm': 'เพื่อยืนยัน',
  'event.working': 'กำลังดำเนินการ…',
  'event.archiveClear': 'จัดเก็บและล้างข้อมูล',
  'event.cancel': 'ยกเลิก',
  'event.clearedBefore': 'ล้างข้อมูลแล้ว คลังข้อมูลอยู่ที่',
  'event.clearedAfter': 'จากนี้ให้สร้างงานถัดไปด้านบน',
  'event.clearedBooths': ' เพิ่มบูธของงานนั้น',
  'event.clearedTiers': ' และตั้งเกณฑ์ของรางวัล',
  'event.clearedThen': ' จากนั้นกด',
  'event.freezing': 'กำลังตรึงตัวเลขรวมลงคลังข้อมูล…',
  'event.archived': 'จัดเก็บแล้ว — ผู้เข้าร่วม {visitors} คน ตรา {stamps} ดวง ของรางวัล {prizes} ชิ้น',
  'event.settling': 'กำลังปรับตัวนับให้ลงตัว…',
  'event.settled': 'ปรับตัวนับให้ลงตัว — เสร็จแล้ว',
  'event.stepBoothStats': 'รีเซ็ตตัวนับของบูธ',
  'event.stepRotate': 'สร้างรหัสลับ QR ใหม่ให้บูธ',
  'event.stepBooths': 'บูธและรูปภาพ',
  'event.stepResetStock': 'คืนสต็อกของรางวัล',
  'event.stepTiers': 'ระดับของรางวัล',
  'event.scope.scans': 'ตรา',
  'event.scope.tierUnlocks': 'สิทธิ์ของรางวัล',
  'event.scope.stockAdjustments': 'ทะเบียนสต็อก',
  'event.scope.draws': 'การจับรางวัลบนเวที',
  'event.scope.buckets': 'เส้นเวลา',
  'event.scope.invites': 'คำเชิญ',
  'event.scope.rateLimits': 'การจำกัดอัตรา',
  'event.scope.counters': 'การออกเลขพาสปอร์ต',
  'event.scope.visitors': 'ความคืบหน้าของผู้เข้าร่วม',
  'event.scope.eventStats': 'ตัวนับของงาน',

  // users and invitations (Users)
  'users.title': 'ผู้ใช้และคำเชิญ',
  'users.makeAdminConfirm': 'ตั้ง {name} เป็นผู้ดูแลระบบหรือไม่ ผู้ดูแลระบบแก้ไขการตั้งค่าได้ทุกอย่าง',
  'users.demoteConfirm': 'ลดสิทธิ์ {name} เป็นผู้เข้าร่วมหรือไม่ หน้าจอบูธและจุดแลกของรางวัลจะใช้ไม่ได้ภายใน 15 นาที',
  'users.deleteConfirm': 'ลบ {name} หรือไม่ ข้อมูลติดต่อจะถูกปิดบังและบัญชีถูกระงับ ส่วนรายการสแกนจะเก็บไว้เพื่อสถิติ',
  'users.deleted': 'ลบแล้ว (แบบชั่วคราว) ปิดบังข้อมูลและระงับบัญชี',
  'users.dismissed': 'ปฏิเสธคำขอและบันทึกไว้แล้ว',
  'users.invitesSent': 'ส่งคำเชิญทางอีเมลแล้ว {count} ฉบับ',
  'users.mailOff': 'ยังไม่ได้ตั้งค่าอีเมล ให้คัดลอกลิงก์ด้านล่างแล้วส่งให้ผู้ดูแลบูธเอง',
  'users.mailFailed': 'ส่งอีเมลไม่สำเร็จ {failed} จาก {total} ฉบับ ให้คัดลอกลิงก์ด้านล่างแล้วส่งเอง',
  'users.showLink': 'แสดงลิงก์ของ {email}',
  'users.resent': 'ส่งใหม่ไปยัง {email} แล้ว',
  'users.resentLink': 'ลิงก์ใหม่พร้อมแล้วด้านล่าง ให้คัดลอกไปใช้ ลิงก์เดิมจะใช้ไม่ได้อีก',
  'users.revokeConfirm': 'เพิกถอนคำเชิญของ {email} หรือไม่ ลิงก์จะใช้ไม่ได้ทันที',
  'users.revoked': 'เพิกถอนคำเชิญของ {email} แล้ว ลิงก์ใช้ไม่ได้อีก',
  'users.reqHeading': 'คำขอสิทธิ์ดูแลซุ้ม',
  'users.reqLead': 'ผู้ที่ขอดูแลซุ้มโดยไม่ได้รับคำเชิญ บัญชีของพวกเขายังไม่เปลี่ยนแปลง การอนุมัติคือสิ่งที่ให้สิทธิ์',
  'users.reqWants': 'ขอดูแลซุ้ม {booth}',
  'users.reqWantsNew': 'ขอเปิดซุ้มใหม่: {booth}',
  'users.reqOverride': '— เปลี่ยนเป็นซุ้มอื่น —',
  'users.reqHeldBy': 'มี {name} ดูแลอยู่แล้ว — การอนุมัติจะเพิ่มผู้ดูแลอีกคน',
  'users.reqApprove': 'อนุมัติ',
  'users.reqReject': 'ปฏิเสธ',
  'users.reqApproved': 'อนุมัติแล้ว ขณะนี้ดูแลซุ้ม {booth} จะมีผลบนอุปกรณ์ภายใน 15 นาที',
  'users.reqRejected': 'ปฏิเสธคำขอแล้ว บัญชีไม่มีการเปลี่ยนแปลง',
  'users.inviteHeading': 'เชิญผู้ดูแลบูธ',
  'users.inviteLead': 'ลิงก์จะให้เขาเข้าสู่ระบบด้วยบัญชีของตนบนเครื่องที่บูธ และเปิดหน้าจอบูธให้ ใช้ได้ครั้งเดียว หมดอายุใน 14 วันหรือเมื่อจบงาน',
  'users.name': 'ชื่อ',
  'users.email': 'อีเมล',
  'users.role': 'บทบาท',
  'users.booth': 'บูธ',
  'users.boothPlaceholder': '— เลือกบูธ —',
  'users.bulkSummary': 'นำเข้าหลายคน: วาง',
  'users.bulkPerLine': 'บรรทัดละหนึ่งคน',
  'users.inviteFilter': 'ตัวกรองคำเชิญ',
  'users.pending': 'รอตอบรับ',
  'users.all': 'ทั้งหมด',
  'users.thStatus': 'สถานะ',
  'users.thSent': 'ส่งเมื่อ',
  'users.resend': 'ส่งใหม่',
  'users.revoke': 'เพิกถอน',
  'users.noPending': 'ไม่มีคำเชิญที่รอตอบรับ',
  'users.usersHeading': 'ผู้ใช้',
  'users.search': 'ค้นหาชื่อ รหัส เลขพาสปอร์ต หรือข้อมูลติดต่อ',
  'users.searchAria': 'ค้นหาผู้ใช้',
  'users.filterRole': 'กรองตามบทบาท',
  'users.allRoles': 'ทุกบทบาท',
  'users.searchingAll': 'กำลังค้นหาจากผู้ใช้ทั้งหมด {count} คน',
  'users.newestFirst': 'ใหม่สุดก่อน หน้าละ 50 รายการ',
  'users.showingPage': 'แสดงรายการที่ {from}–{to}',
  'users.showingPageOf': 'แสดงรายการที่ {from}–{to} จาก {total}',
  'users.page': 'หน้า {n}',
  'users.pages': 'หน้า',
  'users.prev': 'ก่อนหน้า',
  'users.next': 'ถัดไป',
  'users.searching': 'กำลังค้นหา…',
  'users.searchFailed': 'ค้นหาไม่สำเร็จ — ตรวจสอบการเชื่อมต่อแล้วลองอีกครั้ง',
  'users.searchCapped': 'ค้นหาเฉพาะ {count} รายการล่าสุด',
  'users.pressRow': 'กดที่แถวเพื่อเปิดดู',
  'users.thAffiliation': 'สังกัด',
  'users.thCountry': 'ประเทศ',
  'users.thStamps': 'ตรา',
  'users.thPoints': 'คะแนน',
  'users.thRegistered': 'ลงทะเบียนเมื่อ',
  'users.openRow': 'เปิดข้อมูล {name}',
  'users.nothingMatches': 'ไม่พบรายการที่ตรงกัน',
  'users.noUsers': 'ยังไม่มีผู้ใช้',
  'users.inviteLinkFor': 'ลิงก์คำเชิญของ {email}',
  'users.erasureHeading': 'คำขอลบข้อมูล · {count}',
  'users.erasureLead': 'การลบจะเอาบัญชี พาสปอร์ต ตรา และสิทธิ์ของรางวัลออกทั้งหมด แต่ตัวนับของบูธยังอยู่ หากเป็นคำขอซ้ำหรือคำขอทดสอบ ให้ปฏิเสธพร้อมระบุเหตุผล ทั้งสองอย่างถูกบันทึกไว้',
  'users.unknownName': 'ไม่ทราบชื่อ',
  'users.requested': 'ขอเมื่อ {when}',
  'users.eraseNow': 'ลบเดี๋ยวนี้',
  'users.dismiss': 'ปฏิเสธคำขอ',
  'users.reasonAudit': 'เหตุผล (บันทึกไว้ในบันทึกการใช้งาน)',
  'users.reason': 'เหตุผล',
  'users.cancel': 'ยกเลิก',
  'users.eraseWarn': 'การกระทำนี้จะลบบัญชี พาสปอร์ต ตรา และสิทธิ์ของรางวัล ตัวนับของบูธยังอยู่ และย้อนกลับไม่ได้',
  'users.typeToConfirm': 'พิมพ์',
  'users.toConfirm': 'เพื่อยืนยัน',
  'users.erasing': 'กำลังลบ…',
  'users.erasePermanently': 'ลบถาวร',
  'users.createHeading': 'สร้างผู้ใช้ที่เคาน์เตอร์',
  'users.contact': 'อีเมล (หรือเบอร์โทรสำหรับผู้เข้าร่วม)',
  'users.contactAria': 'ข้อมูลติดต่อ',
  'users.visitorType': 'ประเภทผู้เข้าร่วม',
  'users.country': 'ประเทศ',
  'users.institution': 'สถาบัน',
  'users.school': 'สำนักวิชา (มฟล.)',
  'users.schoolAria': 'สำนักวิชา',
  'users.studentId': 'รหัสนักศึกษา (ไม่บังคับ)',
  'users.studentIdAria': 'รหัสนักศึกษา',
  'users.password': 'รหัสผ่าน (ไม่บังคับ · อย่างน้อย 10 ตัวอักษร · ต้องมีอีเมลเป็นข้อมูลติดต่อ)',
  'users.passwordAria': 'รหัสผ่าน',
  'users.creating': 'กำลังสร้าง…',
  'users.createAccount': 'สร้างบัญชี',
  'users.noPasswordNote': 'หากไม่ตั้งรหัสผ่าน ผู้ใช้จะเข้าสู่ระบบด้วย Google ด้วยอีเมลนั้น หรือใช้ “ลืมรหัสผ่าน” เพื่อตั้งรหัสใหม่',
  'users.editDetails': 'แก้ไขข้อมูล',
  'users.userId': 'รหัสผู้ใช้',
  'users.type': 'ประเภท',
  'users.days': 'วันที่มา',
  'users.lastSeen': 'เห็นล่าสุด',
  'users.pointsStamps': '{points} · ตรา {stamps} ดวง',
  'users.ethnicNote': 'ไม่แสดงกลุ่มชาติพันธุ์รายบุคคล ปรากฏเฉพาะเป็นภาพรวมในหน้าภาพรวมเท่านั้น',
  'users.route': 'เส้นทางที่เดิน',
  'users.noStamps': 'ยังไม่มีตรา',
  'users.apply': 'บันทึกบทบาท',
  'users.remove': 'ลบผู้ใช้',
  'users.softDelete': 'ลบแบบชั่วคราว',
  'users.erasePdpa': 'ลบถาวร (PDPA)',
  'users.removeNote': 'การลบแบบชั่วคราวจะปิดบังข้อมูลติดต่อและระงับการเข้าสู่ระบบ ส่วนตรายังอยู่ในสถิติ ส่วนการลบถาวรคือสิทธิที่จะถูกลืม ข้อมูลทุกอย่างของบุคคลนั้นจะหายไป',
  'users.prizes': 'ของรางวัล',
  'users.void': 'ยกเลิก',
  'users.voiding': 'กำลังยกเลิก…',
  'users.voided': 'ยกเลิก {tier} ของ {name} แล้ว ของกลับเข้าสต็อก',
  'users.contactEdit': 'ข้อมูลติดต่อ',
  'users.contactEditNote': '(อีเมลที่กรอกจะเป็นอีเมลสำหรับเข้าสู่ระบบด้วย)',
  'users.mfuOnly': '(เฉพาะ มฟล.)',
  'users.saveChanges': 'บันทึกการแก้ไข',

  // users — send button
  'users.sendInvitation': 'ส่งคำเชิญ',
  'users.sendInvitations': 'ส่งคำเชิญทั้งหมด',

  // prizes — row validation
  'prizes.nPoints': '{n} คะแนน',
  'prizes.needsName': 'ต้องมีชื่อ',
  'prizes.needsThreshold': 'ต้องตั้งเกณฑ์อย่างน้อย 1 คะแนน',
  'prizes.tooHigh': 'ต้องใช้ {points} คะแนน แต่ทั้งงานมีเพียง {available} คะแนน',

  // ---------- booth ratings (pages/admin/Ratings.tsx) ----------
  'admin.ratings.title': 'คะแนนซุ้ม',
  'admin.ratings.lead': 'คะแนน 1 ถึง 5 ดาว ที่ผู้เข้าชมให้หลังรับตราทันที ไม่ระบุตัวตนโดยออกแบบ — ความเห็นที่นี่จึงสืบกลับไปยังบุคคลไม่ได้',
  'admin.ratings.responses': 'จำนวนคะแนน',
  'admin.ratings.average': 'ค่าเฉลี่ยรวมทุกซุ้ม',
  'admin.ratings.rated': 'ซุ้มที่มีคะแนน',
  'admin.ratings.byBooth': 'แยกตามซุ้ม',
  'admin.ratings.booth': 'ซุ้ม',
  'admin.ratings.filterBooth': 'แสดงความเห็นเฉพาะซุ้ม',
  'admin.ratings.allBooths': 'ทุกซุ้ม',
  'admin.ratings.avgShort': 'ค่าเฉลี่ย',
  'admin.ratings.n': 'จำนวน',
  'admin.ratings.spread': 'การกระจาย (1★ ถึง 5★)',
  'admin.ratings.sort': 'การเรียงลำดับ',
  'admin.ratings.sort.best': 'คะแนนสูงสุดก่อน',
  'admin.ratings.sort.worst': 'คะแนนต่ำสุดก่อน',
  'admin.ratings.sort.most': 'จำนวนคะแนนมากที่สุดก่อน',
  'admin.ratings.sort.name': 'ตามชื่อ',
  'admin.ratings.comments': 'ความเห็นเพิ่มเติม',
  'admin.ratings.noComments': 'ยังไม่มีผู้เขียนความเห็น',
  'admin.ratings.capped': 'แสดง {n} รายการล่าสุด ดาวน์โหลด CSV ด้านบนสำหรับตัวเลขทั้งหมด',

  // ---------- festival feedback survey (pages/admin/FestivalSurvey.tsx) ----------
  'admin.fsurvey.title': 'แบบประเมินงาน',
  'admin.fsurvey.lead': 'แบบประเมินของงานที่แสดงบนหน้ารับของรางวัล คำตอบไม่มีรหัสผู้เข้าร่วมกำกับ จึงอ่านได้ทั้งหมดที่นี่',
  'admin.fsurvey.state': 'สถานะ',
  'admin.fsurvey.notInstalled': 'ยังไม่ได้ตั้งค่า',
  'admin.fsurvey.live': 'เผยแพร่แล้ว — ผู้เข้าร่วมเห็นได้',
  'admin.fsurvey.draft': 'บันทึกแล้ว ยังไม่เผยแพร่',
  'admin.fsurvey.counts': '{q} คำถาม · {n} คำตอบ',
  'admin.fsurvey.install': 'โหลดชุดคำถามมาตรฐาน',
  'admin.fsurvey.reinstall': 'รีเซ็ตเป็นชุดคำถามมาตรฐาน',
  'admin.fsurvey.installHint': 'โหลดคำถามก่อน ตรวจทาน แล้วจึงเผยแพร่ ผู้เข้าร่วมจะยังไม่เห็นจนกว่าจะเผยแพร่',
  'admin.fsurvey.installed': 'บันทึกคำถามแล้ว เผยแพร่เมื่อตรวจทานเรียบร้อย',
  'admin.fsurvey.publish': 'เผยแพร่',
  'admin.fsurvey.unpublish': 'ยกเลิกการเผยแพร่',
  'admin.fsurvey.edited': 'ชุดคำถามนี้ถูกแก้ไขต่างจากชุดมาตรฐานแล้ว ไม่เป็นไร — การรีเซ็ตจะเก็บถ้อยคำปัจจุบันไว้เป็นเวอร์ชันเดิมและเริ่มเวอร์ชันใหม่',
  'admin.fsurvey.editHint': 'หากต้องการแก้ถ้อยคำ:',
  'admin.fsurvey.openBuilder': 'เปิดตัวสร้างแบบสอบถาม',
  'admin.fsurvey.results': 'ผลลัพธ์ · {n} คำตอบ',
  'admin.fsurvey.noneYet': 'ยังไม่มีผู้ตอบ',
  'admin.fsurvey.noAnswers': 'ยังไม่มีคำตอบสำหรับข้อนี้',
}
