/**
 * The signed-out screens — the landing page and the four auth pages behind `AuthShell`.
 *
 * These matter more than the staff strings: they are the first thing a Thai visitor meets at the
 * gate, before they have an account, and the only place the language switch is reachable without
 * signing in. Spec §1.4 keeps English as the default for an international audience; Thai is the
 * addition, not the replacement.
 */
export const visitorEn = {
  // Landing
  'home.university': 'Mae Fah Luang University',
  'home.kicker': 'Digital passport',
  'home.lead': 'Collect a stamp at every booth with your own phone, earn points, and trade them for a prize.',
  'home.start': 'Start your passport',
  'home.have': 'I already have a passport',
  'home.opening': 'Opening your passport…',

  // AuthShell chrome
  'auth.back': 'Back',
  'auth.google.opening': 'Opening Google…',

  // Sign up
  'signup.title': 'Create your account',
  'signup.lead': 'One account holds your passport for the whole festival. Sign in again on a new phone and every stamp is still there.',
  'signup.google': 'Sign up with Google',
  'signup.or': 'or with an email',
  'signup.name': 'Your name',
  'signup.namePlaceholder': 'Shown on your passport cover',
  'signup.email': 'Email',
  'signup.emailPlaceholder': 'you@example.com',
  'signup.emailHint': 'We send a one-tap link here to confirm the address is yours.',
  'signup.password': 'Password',
  'signup.passwordPlaceholder': 'At least 8 characters',
  'signup.confirm': 'Confirm password',
  'signup.confirmPlaceholder': 'Type it once more',
  'signup.mismatch': 'The two passwords do not match.',
  'signup.submit': 'Create account',
  'signup.submitting': 'Creating…',
  'signup.privacy': 'By continuing you agree to how MFU handles your details — see the',
  'signup.privacyLink': 'privacy notice',
  'signup.haveOne': 'Already have one?',
  'signup.signIn': 'Sign in',

  // Sign in
  'signin.title': 'Sign in',
  'signin.lead': 'Your passport, stamps and points follow the account — sign in on any phone and they are all there.',
  'signin.google': 'Continue with Google',
  'signin.submitting': 'Signing in…',
  'signin.forgot': 'Forgot your password?',
  'signin.newHere': 'New here?',
  'signin.create': 'Create an account',

  // Passport shell
  'pp.profile': 'Profile',
  'pp.offline': 'Offline — your stamps are saved',
  'pp.offlineNote': 'This page will catch up on its own. You will need a connection to collect a new stamp.',
  'pp.passport': 'Passport',

  // Cover
  'cover.tab': 'Cover',
  'cover.passport': 'Passport',
  'cover.pointsLine': 'points · {done} of {total} stamps',
  'cover.toGo': 'to go',
  'cover.topTier': 'top tier',
  'cover.nextUp': 'Next up:',
  'cover.everyTier': 'You have reached every tier. Show your Prize page at the desk.',
  'cover.goHere': 'Go here next',
  'cover.points': 'points',
  'cover.bangkok': '(Bangkok)',
  'cover.allStamped': 'Every booth stamped. Take your passport to the prize desk.',
  'cover.nothingToday': 'Nothing left to collect today — check back tomorrow for the booths that rotate.',

  // Stamps
  'stamps.title': 'Stamps',
  'stamps.yours': 'Your stamps',
  'stamps.none': 'No stamps yet. Tap',
  'stamps.noneAfter': 'at your first booth.',
  'stamps.stillToCollect': 'Still to collect',
  'stamps.note': 'Rewards may change. Points are set when your stamp is earned. Times shown are Bangkok time.',
  'stamps.fullScreen': 'View full screen',
  'stamps.close': 'Close',
  'stamps.ofTotal': '{done} of {total}',
  'stamps.pointsOnFloor': '{n} points still on the floor',
  'stamps.present': 'Present: {days}',
  'prize.pointsTitle': '{n} points',
  'prize.toGo': '{n} to go',
  'prize.pts': '{n} pts',
  'prize.drawEntry': '+ entry to the closing stage draw',
  'prize.left': '{n} left',
  'prize.leftSession': '{n} left this {session}',
  'prize.collectFrom': 'Collect from {time}',

  // Prize
  'prize.title': 'Prize',
  'prize.entryVisa': 'Entry visa · show this at the prize desk',
  'prize.preparing': 'Preparing your code…',
  'prize.next': 'Next',
  'prize.collected': 'Collected',
  'prize.ready': 'Ready to collect',
  'prize.outOfStock': 'This prize has run out',
  'prize.deskClosed': 'The prize desk is closed',
  'prize.codeLater': 'Your redemption code appears here the moment a tier unlocks. Show it at the prize desk.',

  // Scan
  'scan.title': 'Scan a booth',
  'scan.checking': 'Checking…',
  'scan.offline': 'No connection. A stamp is saved on the server, so this needs a moment of signal — the booth code stays valid while you wait.',
  'scan.manualLabel': 'Or type the 6-character code under the QR',
  'scan.manualPlaceholder': 'ABC234',
  'scan.submit': 'Stamp',
  'scan.checkin': 'Booth check-in',
  'scan.checkingStamp': 'Checking your stamp…',
  'scan.stamping': 'Stamping…',

  // Scan result
  'res.collected': 'Stamp collected',
  'res.unlocked': 'You just unlocked a prize tier. Check the Prize page.',
  'res.another': 'Scan another',
  'res.myStamps': 'My stamps',
  'res.already': 'Already stamped here',
  'res.seeLeft': "See what's left",
  'res.expired': 'That code has expired — the booth screen changes every 20 seconds. Scan it again.',
  'res.invalid': 'Invalid code. Point your camera at the booth screen, or type the 6 characters shown under the QR.',
  'res.rateLimited': 'Too fast — give it a few seconds and try again.',
  'res.notRegistered': 'Create your passport first, then scan.',
  'res.createPassport': 'Create my passport',
  'res.tryAgain': 'Try again',
  'res.answer': 'Answer',
  'res.plusPoints': '+{n} points',
  'res.totalLine': '{booth} · {points} points total · {stamps} stamps',
  'res.alreadyLine': '{booth} is in your passport. Try a booth you have not visited.',
  'res.surveyTitle': 'A few questions',
  'res.surveyCount': '{n} questions from this booth. Optional — your points are already saved.',
  'res.surveyCountOne': '1 question from this booth. Optional — your points are already saved.',

  // Visitor survey
  'vsurvey.opening': 'Opening the questions…',
  'vsurvey.thankYou': 'Thank you',
  'vsurvey.scanAnother': 'Scan another booth',
  'vsurvey.myStamps': 'My stamps',
  'vsurvey.already': "You have already answered this booth's questions. Thank you.",
  'vsurvey.nothing': 'This booth is not asking anything at the moment.',
  'vsurvey.sending': 'Sending…',
  'vsurvey.submit': 'Submit',
  'vsurvey.booth': 'Booth',
  'vsurvey.hasAnswers': '{booth} has your answers.',
  'vsurvey.missing': '{n} required questions still to answer.',
  'vsurvey.missingOne': '1 required question still to answer.',
  'vsurvey.skip': 'Skip — I would rather keep scanning',

  // Join — the registration form
  'join.title': 'Start your passport',
  'join.lead': 'Under a minute — a few details for the organisers, then your passport opens.',
  'join.signedInAs': 'Signed in as',
  'join.notYou': 'Not you?',
  'join.name': 'Your name',
  'join.namePlaceholder': 'Shown on your passport cover',
  'join.iAmA': 'I am a',
  'join.type.student': 'Student',
  'join.type.staff': 'Staff',
  'join.type.alumni': 'Alumni',
  'join.type.guest': 'External guest',
  'join.optional': '(optional)',
  'join.studentId': 'Student / staff ID',
  'join.institution': 'University / institution',
  'join.startTyping': 'Start typing…',
  'join.institutionName': 'Institution name',
  'join.school': 'School / office',
  'join.country': 'Country of origin',
  'join.ethnic': 'Ethnic group / community',
  'join.ethnicNote': 'MFU serves students from many communities across the Mekong region. The Office of International Affairs asks this only to show, in aggregate, that the festival reached them. It is never shown with your name.',
  'join.ethnicPlaceholder': 'Type, choose, or leave blank',
  'join.preferNot': 'Prefer not to say',
  'join.ethnicConsent': 'I consent to my ethnic group being collected for aggregate event statistics only.',
  'join.ethnicConsentNote': '(Leave unticked and it will not be stored.)',
  'join.consent': 'I consent to MFU collecting the details above and my booth check-in times for running this activity and for aggregate event statistics, kept for 90 days after the event.',
  'join.privacy': 'Privacy notice',
  'join.needConsent': 'Please tick the consent box to continue.',
  'join.submit': 'Create my passport',
  'join.submitting': 'Creating…',

  // Invitation
  'inv.reading': 'Reading your invitation…',
  'inv.unusable': 'This invitation cannot be used',
  'inv.accepted': 'This invitation has already been used. If that was you, sign in on that device — or ask the admin to resend it.',
  'inv.expired': 'This invitation has expired. Ask the admin to resend it.',
  'inv.revoked': 'This invitation was withdrawn.',
  'inv.invalid': 'This link is not a valid invitation.',
  'inv.signIn': 'Sign in',
  'inv.backToStart': 'Back to the start',
  'inv.invitedAdmin': 'You are invited to run the admin dashboard.',
  'inv.invitedBooth': 'You are invited to run the booth screen for {booth}.',
  'inv.checking': 'Checking this device…',
  'inv.signInAs': 'Sign in as {email} to accept.',
  'inv.google': 'Continue with Google',
  'inv.useEmail': 'Use an email and password',
  'inv.noAccount': 'No account for that address yet? Create one',
  'inv.signedInAs': 'Signed in as {email}.',
  'inv.settingUp': 'Setting up…',
  'inv.acceptAdmin': 'Accept and open the dashboard',
  'inv.acceptBooth': 'Accept and open my booth',
  'inv.signOutDevice': 'Sign out of this device',
} as const

export const visitorTh: Record<keyof typeof visitorEn, string> = {
  'home.university': 'มหาวิทยาลัยแม่ฟ้าหลวง',
  'home.kicker': 'พาสปอร์ตดิจิทัล',
  'home.lead': 'สะสมตราประทับจากทุกบูธด้วยโทรศัพท์ของคุณ รับคะแนน แล้วนำไปแลกของรางวัล',
  'home.start': 'เริ่มใช้พาสปอร์ต',
  'home.have': 'ฉันมีพาสปอร์ตอยู่แล้ว',
  'home.opening': 'กำลังเปิดพาสปอร์ตของคุณ…',

  'auth.back': 'ย้อนกลับ',
  'auth.google.opening': 'กำลังเปิด Google…',

  'signup.title': 'สร้างบัญชีของคุณ',
  'signup.lead': 'บัญชีเดียวใช้กับพาสปอร์ตตลอดทั้งงาน เข้าสู่ระบบอีกครั้งบนโทรศัพท์เครื่องใหม่ ตราประทับทุกดวงยังอยู่ครบ',
  'signup.google': 'สมัครด้วย Google',
  'signup.or': 'หรือใช้อีเมล',
  'signup.name': 'ชื่อของคุณ',
  'signup.namePlaceholder': 'ชื่อที่แสดงบนปกพาสปอร์ต',
  'signup.email': 'อีเมล',
  'signup.emailPlaceholder': 'you@example.com',
  'signup.emailHint': 'เราจะส่งลิงก์ยืนยันไปที่อีเมลนี้ เพื่อยืนยันว่าเป็นอีเมลของคุณ',
  'signup.password': 'รหัสผ่าน',
  'signup.passwordPlaceholder': 'อย่างน้อย 8 ตัวอักษร',
  'signup.confirm': 'ยืนยันรหัสผ่าน',
  'signup.confirmPlaceholder': 'พิมพ์รหัสผ่านอีกครั้ง',
  'signup.mismatch': 'รหัสผ่านทั้งสองช่องไม่ตรงกัน',
  'signup.submit': 'สร้างบัญชี',
  'signup.submitting': 'กำลังสร้างบัญชี…',
  'signup.privacy': 'การดำเนินการต่อถือว่าคุณยอมรับวิธีที่ มฟล. จัดการข้อมูลของคุณ — ดู',
  'signup.privacyLink': 'ประกาศความเป็นส่วนตัว',
  'signup.haveOne': 'มีบัญชีอยู่แล้ว?',
  'signup.signIn': 'เข้าสู่ระบบ',

  'signin.title': 'เข้าสู่ระบบ',
  'signin.lead': 'พาสปอร์ต ตราประทับ และคะแนนของคุณผูกกับบัญชี เข้าสู่ระบบจากโทรศัพท์เครื่องใดก็เห็นครบทั้งหมด',
  'signin.google': 'เข้าสู่ระบบด้วย Google',
  'signin.submitting': 'กำลังเข้าสู่ระบบ…',
  'signin.forgot': 'ลืมรหัสผ่าน?',
  'signin.newHere': 'เพิ่งเคยใช้ครั้งแรก?',
  'signin.create': 'สร้างบัญชีใหม่',

  'pp.profile': 'โปรไฟล์',
  'pp.offline': 'ออฟไลน์ — ตราประทับของคุณถูกบันทึกไว้แล้ว',
  'pp.offlineNote': 'หน้านี้จะอัปเดตเองเมื่อกลับมาออนไลน์ แต่การรับตราประทับใหม่ต้องใช้อินเทอร์เน็ต',
  'pp.passport': 'พาสปอร์ต',

  'cover.tab': 'ปกพาสปอร์ต',
  'cover.passport': 'พาสปอร์ต',
  'cover.pointsLine': 'คะแนน · {done} จาก {total} ตราประทับ',
  'cover.toGo': 'อีก',
  'cover.topTier': 'ระดับสูงสุด',
  'cover.nextUp': 'ระดับถัดไป:',
  'cover.everyTier': 'คุณได้รับครบทุกระดับแล้ว นำหน้าของรางวัลไปแสดงที่จุดแลกของรางวัล',
  'cover.goHere': 'ไปบูธนี้ต่อ',
  'cover.points': 'คะแนน',
  'cover.bangkok': '(เวลากรุงเทพฯ)',
  'cover.allStamped': 'สะสมครบทุกบูธแล้ว นำพาสปอร์ตไปที่จุดแลกของรางวัลได้เลย',
  'cover.nothingToday': 'วันนี้ไม่มีบูธให้สะสมเพิ่มแล้ว — พรุ่งนี้ยังมีบูธที่หมุนเวียนมาใหม่',

  'stamps.title': 'ตราประทับ',
  'stamps.yours': 'ตราประทับของคุณ',
  'stamps.none': 'ยังไม่มีตราประทับ กด',
  'stamps.noneAfter': 'ที่บูธแรกของคุณ',
  'stamps.stillToCollect': 'ยังเก็บไม่ครบ',
  'stamps.note': 'ของรางวัลอาจเปลี่ยนแปลงได้ คะแนนจะถูกกำหนดเมื่อคุณได้รับตราประทับ เวลาที่แสดงเป็นเวลากรุงเทพฯ',
  'stamps.fullScreen': 'ดูแบบเต็มจอ',
  'stamps.close': 'ปิด',
  'stamps.ofTotal': '{done} จาก {total}',
  'stamps.pointsOnFloor': 'ยังมีอีก {n} คะแนนในงาน',
  'stamps.present': 'เปิดบูธ: {days}',
  'prize.pointsTitle': '{n} คะแนน',
  'prize.toGo': 'อีก {n}',
  'prize.pts': '{n} คะแนน',
  'prize.drawEntry': '+ สิทธิ์ลุ้นรางวัลบนเวทีช่วงปิดงาน',
  'prize.left': 'เหลือ {n} ชิ้น',
  'prize.leftSession': 'เหลือ {n} ชิ้นในรอบ{session}',
  'prize.collectFrom': 'รับได้ตั้งแต่ {time}',

  'prize.title': 'ของรางวัล',
  'prize.entryVisa': 'วีซ่าเข้างาน · แสดงรหัสนี้ที่จุดแลกของรางวัล',
  'prize.preparing': 'กำลังเตรียมรหัสของคุณ…',
  'prize.next': 'ถัดไป',
  'prize.collected': 'รับแล้ว',
  'prize.ready': 'พร้อมให้รับ',
  'prize.outOfStock': 'ของรางวัลนี้หมดแล้ว',
  'prize.deskClosed': 'จุดแลกของรางวัลปิดอยู่',
  'prize.codeLater': 'รหัสสำหรับแลกของรางวัลจะปรากฏที่นี่ทันทีที่คุณถึงระดับรางวัล แล้วนำไปแสดงที่จุดแลกของรางวัล',

  'scan.title': 'สแกนบูธ',
  'scan.checking': 'กำลังตรวจสอบ…',
  'scan.offline': 'ไม่มีการเชื่อมต่อ ตราประทับจะถูกบันทึกบนเซิร์ฟเวอร์ จึงต้องใช้สัญญาณสักครู่ — รหัสของบูธยังใช้ได้ระหว่างที่รอ',
  'scan.manualLabel': 'หรือพิมพ์รหัส 6 ตัวอักษรที่อยู่ใต้ QR',
  'scan.manualPlaceholder': 'ABC234',
  'scan.submit': 'รับตราประทับ',
  'scan.checkin': 'เช็คอินที่บูธ',
  'scan.checkingStamp': 'กำลังตรวจสอบตราประทับของคุณ…',
  'scan.stamping': 'กำลังประทับตรา…',

  'res.collected': 'ได้รับตราประทับแล้ว',
  'res.unlocked': 'คุณเพิ่งปลดล็อกระดับของรางวัล ดูได้ที่หน้าของรางวัล',
  'res.another': 'สแกนบูธอื่น',
  'res.myStamps': 'ตราประทับของฉัน',
  'res.already': 'บูธนี้ประทับตราไปแล้ว',
  'res.seeLeft': 'ดูว่าเหลือบูธไหนบ้าง',
  'res.expired': 'รหัสนี้หมดอายุแล้ว — หน้าจอบูธเปลี่ยนรหัสทุก 20 วินาที กรุณาสแกนใหม่อีกครั้ง',
  'res.invalid': 'รหัสไม่ถูกต้อง กรุณาเล็งกล้องไปที่หน้าจอบูธ หรือพิมพ์รหัส 6 ตัวอักษรที่อยู่ใต้ QR',
  'res.rateLimited': 'เร็วเกินไป — รอสักครู่แล้วลองใหม่อีกครั้ง',
  'res.notRegistered': 'กรุณาสร้างพาสปอร์ตของคุณก่อน แล้วจึงสแกน',
  'res.createPassport': 'สร้างพาสปอร์ตของฉัน',
  'res.tryAgain': 'ลองอีกครั้ง',
  'res.answer': 'ตอบคำถาม',
  'res.plusPoints': '+{n} คะแนน',
  'res.totalLine': '{booth} · รวม {points} คะแนน · {stamps} ตราประทับ',
  'res.alreadyLine': '{booth} อยู่ในพาสปอร์ตของคุณแล้ว ลองบูธที่ยังไม่ได้ไปดูสิ',
  'res.surveyTitle': 'คำถามสั้น ๆ',
  'res.surveyCount': 'มี {n} คำถามจากบูธนี้ ตอบหรือไม่ก็ได้ — คะแนนของคุณถูกบันทึกแล้ว',
  'res.surveyCountOne': 'มี 1 คำถามจากบูธนี้ ตอบหรือไม่ก็ได้ — คะแนนของคุณถูกบันทึกแล้ว',

  'vsurvey.opening': 'กำลังเปิดคำถาม…',
  'vsurvey.thankYou': 'ขอบคุณ',
  'vsurvey.scanAnother': 'สแกนบูธอื่น',
  'vsurvey.myStamps': 'ตราประทับของฉัน',
  'vsurvey.already': 'คุณตอบคำถามของบูธนี้ไปแล้ว ขอบคุณค่ะ',
  'vsurvey.nothing': 'ขณะนี้บูธนี้ยังไม่มีคำถาม',
  'vsurvey.sending': 'กำลังส่ง…',
  'vsurvey.submit': 'ส่งคำตอบ',
  'vsurvey.booth': 'บูธ',
  'vsurvey.hasAnswers': '{booth} ได้รับคำตอบของคุณแล้ว',
  'vsurvey.missing': 'ยังมีคำถามที่ต้องตอบอีก {n} ข้อ',
  'vsurvey.missingOne': 'ยังมีคำถามที่ต้องตอบอีก 1 ข้อ',
  'vsurvey.skip': 'ข้ามไปก่อน — ขอสแกนบูธต่อ',

  'join.title': 'เริ่มใช้พาสปอร์ตของคุณ',
  'join.lead': 'ใช้เวลาไม่ถึงหนึ่งนาที — กรอกข้อมูลสั้น ๆ ให้ผู้จัดงาน แล้วพาสปอร์ตของคุณจะเปิดทันที',
  'join.signedInAs': 'เข้าสู่ระบบในชื่อ',
  'join.notYou': 'ไม่ใช่คุณ?',
  'join.name': 'ชื่อของคุณ',
  'join.namePlaceholder': 'ชื่อที่แสดงบนปกพาสปอร์ต',
  'join.iAmA': 'ฉันคือ',
  'join.type.student': 'นักศึกษา',
  'join.type.staff': 'บุคลากร',
  'join.type.alumni': 'ศิษย์เก่า',
  'join.type.guest': 'ผู้เข้าชมจากภายนอก',
  'join.optional': '(ไม่บังคับ)',
  'join.studentId': 'รหัสนักศึกษา / รหัสบุคลากร',
  'join.institution': 'มหาวิทยาลัย / สถาบัน',
  'join.startTyping': 'เริ่มพิมพ์…',
  'join.institutionName': 'ชื่อสถาบัน',
  'join.school': 'สำนักวิชา / หน่วยงาน',
  'join.country': 'ประเทศที่มาจาก',
  'join.ethnic': 'กลุ่มชาติพันธุ์ / ชุมชน',
  'join.ethnicNote': 'มฟล. มีนักศึกษาจากหลายชุมชนทั่วอนุภูมิภาคลุ่มน้ำโขง ส่วนพัฒนาความสัมพันธ์ระหว่างประเทศขอข้อมูลนี้เพื่อแสดงในภาพรวมว่างานเข้าถึงกลุ่มใดบ้างเท่านั้น และจะไม่แสดงคู่กับชื่อของคุณ',
  'join.ethnicPlaceholder': 'พิมพ์ เลือก หรือเว้นว่างไว้ก็ได้',
  'join.preferNot': 'ไม่ประสงค์ระบุ',
  'join.ethnicConsent': 'ฉันยินยอมให้เก็บข้อมูลกลุ่มชาติพันธุ์เพื่อใช้เป็นสถิติภาพรวมของงานเท่านั้น',
  'join.ethnicConsentNote': '(หากไม่ติ๊ก ระบบจะไม่จัดเก็บข้อมูลนี้)',
  'join.consent': 'ฉันยินยอมให้ มฟล. เก็บข้อมูลข้างต้นและเวลาที่เช็คอินตามบูธ เพื่อใช้ดำเนินกิจกรรมนี้และจัดทำสถิติภาพรวมของงาน โดยเก็บไว้ 90 วันหลังจบงาน',
  'join.privacy': 'ประกาศความเป็นส่วนตัว',
  'join.needConsent': 'กรุณาติ๊กช่องยินยอมเพื่อดำเนินการต่อ',
  'join.submit': 'สร้างพาสปอร์ตของฉัน',
  'join.submitting': 'กำลังสร้าง…',

  'inv.reading': 'กำลังอ่านคำเชิญของคุณ…',
  'inv.unusable': 'ไม่สามารถใช้คำเชิญนี้ได้',
  'inv.accepted': 'คำเชิญนี้ถูกใช้ไปแล้ว หากเป็นคุณเอง กรุณาเข้าสู่ระบบบนอุปกรณ์เครื่องนั้น หรือแจ้งผู้ดูแลระบบให้ส่งคำเชิญใหม่',
  'inv.expired': 'คำเชิญนี้หมดอายุแล้ว กรุณาแจ้งผู้ดูแลระบบให้ส่งใหม่',
  'inv.revoked': 'คำเชิญนี้ถูกยกเลิกแล้ว',
  'inv.invalid': 'ลิงก์นี้ไม่ใช่คำเชิญที่ถูกต้อง',
  'inv.signIn': 'เข้าสู่ระบบ',
  'inv.backToStart': 'กลับไปหน้าแรก',
  'inv.invitedAdmin': 'คุณได้รับเชิญให้ดูแลแดชบอร์ดผู้ดูแลระบบ',
  'inv.invitedBooth': 'คุณได้รับเชิญให้ดูแลหน้าจอบูธของ {booth}',
  'inv.checking': 'กำลังตรวจสอบอุปกรณ์นี้…',
  'inv.signInAs': 'กรุณาเข้าสู่ระบบด้วย {email} เพื่อรับคำเชิญ',
  'inv.google': 'เข้าสู่ระบบด้วย Google',
  'inv.useEmail': 'ใช้อีเมลและรหัสผ่าน',
  'inv.noAccount': 'ยังไม่มีบัญชีสำหรับอีเมลนี้? สร้างบัญชีใหม่',
  'inv.signedInAs': 'เข้าสู่ระบบในชื่อ {email}',
  'inv.settingUp': 'กำลังตั้งค่า…',
  'inv.acceptAdmin': 'รับคำเชิญและเปิดแดชบอร์ด',
  'inv.acceptBooth': 'รับคำเชิญและเปิดหน้าจอบูธ',
  'inv.signOutDevice': 'ออกจากระบบบนอุปกรณ์นี้',
}
