/**
 * The 76 booths of MFU Go Global 2026, from the official booth sheet
 * (docs.google.com/spreadsheets/d/1YSl-NRrnJCRqgCQE8EtN3X-JazTP4krxe18n5mFaVK0, gid=0).
 *
 * Generated — do not hand-edit. Re-run scripts/build-booths.py after the sheet changes,
 * then `npm run seed` to push. See docs/booth-seed-notes.md for the decisions behind it
 * and for the rows still waiting on the organisers.
 *
 * Ids are the sheet's own booth codes so that signage, the sheet and Firestore agree.
 * Every booth is worth the same base points; the quiet/busy adjustment (shared/points.ts)
 * is what makes a lightly-visited booth worth more for a while.
 */
import type { BoothCategory, Zone } from './shared/model'

export interface SeedBooth {
  id: string
  nameEn: string
  nameTh: string
  shortName: string
  hostUnit: string
  category: BoothCategory
  location: string
  descriptionEn: string
  accentColor: string
  zone: Zone
  isPrizeDesk: boolean
}

/** GRD's own booth — where the single main-organiser gift is handed over. */
export const PRIZE_DESK_BOOTH_ID = 'ED8'

export const SEED_BOOTHS: SeedBooth[] = [
  { id: 'ED1', nameEn: 'The Mekong-Australia Partnership Support Unit', nameTh: 'The Mekong-Australia Partnership Support Unit', shortName: 'Mekong-Australia', hostUnit: 'MAP SU, Australia Embassy', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'Information on Australian education funding and opportunities', accentColor: '#EF5F5F', zone: 'entrance', isPrizeDesk: false },
  { id: 'ED2', nameEn: 'British Council Thailand', nameTh: 'British Council Thailand', shortName: 'British Council', hostUnit: 'British Council Thailand', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'Information on UK education funding and opportunities', accentColor: '#0FAFD0', zone: 'entrance', isPrizeDesk: false },
  { id: 'ED3', nameEn: 'Campus France Thailand', nameTh: 'Campus France Thailand', shortName: 'Campus France', hostUnit: 'French Embassy', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'Information on French education funding by Campus France Thailand', accentColor: '#4C764F', zone: 'entrance', isPrizeDesk: false },
  { id: 'ED4', nameEn: 'Thailand-U.S. Educational Foundation', nameTh: 'Thailand-U.S. Educational Foundation', shortName: 'Fulbright', hostUnit: 'Fulbright Thailand', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'Information on U.S. education funding and opportunities', accentColor: '#F5C63C', zone: 'entrance', isPrizeDesk: false },
  { id: 'ED5', nameEn: 'Waiting', nameTh: 'Waiting', shortName: 'TBC', hostUnit: 'School of Medicine', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'Information on Indian education funding and opportunities', accentColor: '#FF919C', zone: 'entrance', isPrizeDesk: false },
  { id: 'ED6', nameEn: 'Taiwan Education Center, Thailand', nameTh: 'Taiwan Education Center, Thailand', shortName: 'Taiwan EC', hostUnit: 'Taiwan Education Center Thailand', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'Information on Taiwan education funding and opportunities', accentColor: '#F0A445', zone: 'entrance', isPrizeDesk: false },
  { id: 'ED7', nameEn: 'TOEFL/IELTS Testing Center', nameTh: 'TOEFL/IELTS Testing Center', shortName: 'TOEFL/IELTS', hostUnit: 'Chiang Rai Rajabhat University', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'TOEFL and IELTS examination information', accentColor: '#45CFC0', zone: 'entrance', isPrizeDesk: false },
  { id: 'ED8', nameEn: 'MFU Go Global', nameTh: 'MFU Go Global', shortName: 'MFU Go Global', hostUnit: 'GRD', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'International exchange programs and funding for MFU students', accentColor: '#E08761', zone: 'entrance', isPrizeDesk: true },
  { id: 'ED9', nameEn: 'Match the International Internship', nameTh: 'Match the International Internship', shortName: 'Internships', hostUnit: 'Student Employment and Internship Division', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'International internship opportunities for MFU students', accentColor: '#2F5D3E', zone: 'entrance', isPrizeDesk: false },
  { id: 'ED10', nameEn: 'Eco-printing & Vegan Leather Workshop', nameTh: 'Eco-printing & Vegan Leather Workshop', shortName: 'Eco-printing', hostUnit: 'School of Science', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'Innovation workshops on eco-printing and vegan leather', accentColor: '#EF5F5F', zone: 'entrance', isPrizeDesk: false },
  { id: 'ED11', nameEn: 'MFU Nursing | Go Global', nameTh: 'MFU Nursing | Go Global', shortName: 'Nursing Global', hostUnit: 'School of Nursing 2', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'International nursing education, student exchange, research, and partnerships', accentColor: '#0FAFD0', zone: 'entrance', isPrizeDesk: false },
  { id: 'ED12', nameEn: 'Baan Lamduan', nameTh: 'Baan Lamduan', shortName: 'Baan Lamduan', hostUnit: 'MFU Medical Center Hospital', category: 'wellness', location: 'Wellness', descriptionEn: 'MFU Premium Care & Recovery Center for elderly care and rehabilitation', accentColor: '#4C764F', zone: 'entrance', isPrizeDesk: false },
  { id: 'ED13', nameEn: 'MFU Nursing | CPR Experience', nameTh: 'MFU Nursing | CPR Experience', shortName: 'CPR Experience', hostUnit: 'School of Nursing 1', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'CPR training through games, simulations, and hands-on practice', accentColor: '#F5C63C', zone: 'entrance', isPrizeDesk: false },
  { id: 'ED14', nameEn: 'Find Your Personal Color', nameTh: 'Find Your Personal Color', shortName: 'Personal Color', hostUnit: 'School of Cosmetic Science', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'Personal color analysis based on skin, hair, eye tone and undertone', accentColor: '#FF919C', zone: 'entrance', isPrizeDesk: false },
  { id: 'ED15', nameEn: 'Lifelong Journey', nameTh: 'Lifelong Journey', shortName: 'Lifelong Journey', hostUnit: 'MLII', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'Online courses in Chinese and Anatomy; VR innovation demonstrations', accentColor: '#F0A445', zone: 'entrance', isPrizeDesk: false },
  { id: 'ED16', nameEn: 'Global Compass', nameTh: 'Global Compass', shortName: 'Global Compass', hostUnit: 'Student Development Affairs 1', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'Game-based activity exploring freedom with responsibility and respect', accentColor: '#45CFC0', zone: 'entrance', isPrizeDesk: false },
  { id: 'ED17', nameEn: 'Act for Earth', nameTh: 'Act for Earth', shortName: 'Act for Earth', hostUnit: 'Student Development Affairs 2', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'Game activity promoting environmental awareness and conservation', accentColor: '#E08761', zone: 'entrance', isPrizeDesk: false },
  { id: 'ED18', nameEn: 'Touch to Connect', nameTh: 'Touch to Connect', shortName: 'Touch to Connect', hostUnit: 'Student Development Affairs 3', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'Braille writing activity in Thai, Chinese, and English on stickers', accentColor: '#2F5D3E', zone: 'entrance', isPrizeDesk: false },
  { id: 'ED19', nameEn: 'Fund & Friends', nameTh: 'Fund & Friends', shortName: 'Fund & Friends', hostUnit: 'Student Development Affairs 4', category: 'educational', location: 'Educational & Study Abroad', descriptionEn: 'Information on international student welfare and scholarships with games', accentColor: '#EF5F5F', zone: 'entrance', isPrizeDesk: false },
  { id: 'CL20', nameEn: 'Dress Like Chinese', nameTh: 'Dress Like Chinese', shortName: 'Dress Like Chinese', hostUnit: 'School of Sinology 1', category: 'cultural', location: 'Cultural', descriptionEn: 'Chinese culture learning through traditional clothing', accentColor: '#0FAFD0', zone: 'entrance', isPrizeDesk: false },
  { id: 'CL21', nameEn: 'Chinese Connection Knot', nameTh: 'Chinese Connection Knot', shortName: 'Chinese Knot', hostUnit: 'School of Sinology 2', category: 'cultural', location: 'Cultural', descriptionEn: 'Chinese culture learning through traditional knot-tying', accentColor: '#4C764F', zone: 'entrance', isPrizeDesk: false },
  { id: 'CL22', nameEn: 'Chinese Ink & Art', nameTh: 'Chinese Ink & Art', shortName: 'Chinese Ink & Art', hostUnit: 'Thai-Chinese Education Association', category: 'cultural', location: 'Cultural', descriptionEn: 'Chinese culture learning through brush painting', accentColor: '#F5C63C', zone: 'entrance', isPrizeDesk: false },
  { id: 'CL23', nameEn: 'Dolanan Anak: Games, Songs & Traditions', nameTh: 'Dolanan Anak: Games, Songs & Traditions', shortName: 'Dolanan Anak', hostUnit: 'Anti-Aging and Regenerative Medicine', category: 'cultural', location: 'Cultural', descriptionEn: 'Indonesian (Central Java) culture learning through games and traditions', accentColor: '#FF919C', zone: 'entrance', isPrizeDesk: false },
  { id: 'CL24', nameEn: 'Lanna Dreamcatcher Craft', nameTh: 'Lanna Dreamcatcher Craft', shortName: 'Lanna Dreamcatcher', hostUnit: 'Institute for Mekong Civilization, Art, Culture', category: 'cultural', location: 'Cultural', descriptionEn: 'Northern Thai culture learning through dreamcatcher weaving', accentColor: '#F0A445', zone: 'entrance', isPrizeDesk: false },
  { id: 'CL25', nameEn: 'Living Heritage in Action', nameTh: 'Living Heritage in Action', shortName: 'Living Heritage', hostUnit: 'School of Social Innovation', category: 'cultural', location: 'Cultural', descriptionEn: 'Indonesian culture through Angklung music and Tari Indang dance', accentColor: '#45CFC0', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD26', nameEn: 'Global Sips', nameTh: 'Global Sips', shortName: 'Global Sips', hostUnit: 'Tea and Coffee Institution', category: 'food', location: 'International Food & Culture', descriptionEn: 'International culture learning through food and beverages', accentColor: '#E08761', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD27', nameEn: 'Healthy Local Food in Japan', nameTh: 'Healthy Local Food in Japan', shortName: 'Japan (Izakaya)', hostUnit: 'School of Agricultural Industry 1', category: 'food', location: 'International Food & Culture', descriptionEn: 'Japanese healthy local cuisine (Izakaya)', accentColor: '#2F5D3E', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD28', nameEn: 'Healthy Local Food in Myanmar', nameTh: 'Healthy Local Food in Myanmar', shortName: 'Myanmar', hostUnit: 'School of Agricultural Industry 2', category: 'food', location: 'International Food & Culture', descriptionEn: 'Myanmar healthy local cuisine', accentColor: '#EF5F5F', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD29', nameEn: 'Healthy Local Food in Vietnam', nameTh: 'Healthy Local Food in Vietnam', shortName: 'Vietnam (Noodle)', hostUnit: 'School of Agricultural Industry 3', category: 'food', location: 'International Food & Culture', descriptionEn: 'Vietnamese healthy local cuisine (Noodle)', accentColor: '#0FAFD0', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD30', nameEn: 'Healthy Local Food in Indonesia', nameTh: 'Healthy Local Food in Indonesia', shortName: 'Indonesia', hostUnit: 'School of Agricultural Industry 4', category: 'food', location: 'International Food & Culture', descriptionEn: 'Indonesian healthy local cuisine (Nasi Liwet and Ayam Serundeng)', accentColor: '#4C764F', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD31', nameEn: 'Healthy Local Food in India', nameTh: 'Healthy Local Food in India', shortName: 'India', hostUnit: 'School of Agricultural Industry 5', category: 'food', location: 'International Food & Culture', descriptionEn: 'Indian healthy local cuisine', accentColor: '#F5C63C', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD32', nameEn: 'A Sip of India', nameTh: 'A Sip of India', shortName: 'A Sip of India', hostUnit: 'Consulate of India in Chiang Mai', category: 'food', location: 'International Food & Culture', descriptionEn: 'International culture learning through Indian food', accentColor: '#FF919C', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD33', nameEn: 'Healthy Local Food in Tai Yai', nameTh: 'Healthy Local Food in Tai Yai', shortName: 'Tai Yai', hostUnit: 'School of Agricultural Industry 7', category: 'food', location: 'International Food & Culture', descriptionEn: 'Tai Yai healthy local cuisine', accentColor: '#F0A445', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD34', nameEn: 'Healthy Local Food in Karen', nameTh: 'Healthy Local Food in Karen', shortName: 'Karen', hostUnit: 'School of Agricultural Industry 8', category: 'food', location: 'International Food & Culture', descriptionEn: 'Karen healthy local cuisine', accentColor: '#45CFC0', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD35', nameEn: 'Healthy Local Food (Ethnic Minority) I', nameTh: 'Healthy Local Food (Ethnic Minority) I', shortName: 'Local Food I', hostUnit: 'School of Agricultural Industry 9', category: 'food', location: 'International Food & Culture', descriptionEn: 'Ethnic minority healthy local cuisine', accentColor: '#E08761', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD36', nameEn: 'Healthy Local Food (Ethnic Minority) II', nameTh: 'Healthy Local Food (Ethnic Minority) II', shortName: 'Local Food II', hostUnit: 'School of Agricultural Industry 10', category: 'food', location: 'International Food & Culture', descriptionEn: 'Ethnic minority healthy local cuisine', accentColor: '#2F5D3E', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD37', nameEn: 'Siam Spice', nameTh: 'Siam Spice', shortName: 'Siam Spice', hostUnit: 'School of Liberal Arts 1', category: 'food', location: 'International Food & Culture', descriptionEn: 'Thai international cuisine (Hor Mok Talay)', accentColor: '#EF5F5F', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD38', nameEn: 'Flavors of Japan', nameTh: 'Flavors of Japan', shortName: 'Flavors of Japan', hostUnit: 'School of Liberal Arts 2', category: 'food', location: 'International Food & Culture', descriptionEn: 'Japanese international cuisine (Chirashi Sushi)', accentColor: '#0FAFD0', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD39', nameEn: 'Nusantara Delights', nameTh: 'Nusantara Delights', shortName: 'Nusantara', hostUnit: 'School of Liberal Arts 3', category: 'food', location: 'International Food & Culture', descriptionEn: 'Indonesian international cuisine (Ayam Rendang)', accentColor: '#4C764F', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD40', nameEn: 'Seoul TteokBokki', nameTh: 'Seoul TteokBokki', shortName: 'Seoul Tteokbokki', hostUnit: 'School of Liberal Arts 4', category: 'food', location: 'International Food & Culture', descriptionEn: 'Korean international cuisine (Spicy Rice Cakes)', accentColor: '#F5C63C', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD41', nameEn: 'The American Melting Pot', nameTh: 'The American Melting Pot', shortName: 'Melting Pot', hostUnit: 'School of Liberal Arts 5', category: 'food', location: 'International Food & Culture', descriptionEn: 'American international cuisine (Cheesesteak Rolls, Caesar Salad)', accentColor: '#FF919C', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD42', nameEn: 'Assorted Burmese Fritters', nameTh: 'Assorted Burmese Fritters', shortName: 'Burmese Fritters', hostUnit: 'School of Liberal Arts 6', category: 'food', location: 'International Food & Culture', descriptionEn: 'Burmese international cuisine (Dok Hto sticks)', accentColor: '#F0A445', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD43', nameEn: 'Global Table — Korea', nameTh: 'Global Table — Korea', shortName: 'Korea', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Korean cuisine (hotteok, kimchi soup, fried chicken, tteokbokki)', accentColor: '#45CFC0', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD44', nameEn: 'Global Table — Japan', nameTh: 'Global Table — Japan', shortName: 'Japan', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Japanese cuisine (yakitori, mochi, yakisoba, sushi)', accentColor: '#E08761', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD45', nameEn: 'Global Table — Germany', nameTh: 'Global Table — Germany', shortName: 'Germany', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'German cuisine (potato salad, apple pastries)', accentColor: '#2F5D3E', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD46', nameEn: 'Global Table — Indonesia', nameTh: 'Global Table — Indonesia', shortName: 'Indonesia', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Indonesian cuisine (Siomay steamed dumplings)', accentColor: '#EF5F5F', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD47', nameEn: 'Global Table — Mexico', nameTh: 'Global Table — Mexico', shortName: 'Mexico', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Mexican cuisine (nachos, tacos, salsa)', accentColor: '#0FAFD0', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD48', nameEn: 'Global Table — Czechia', nameTh: 'Global Table — Czechia', shortName: 'Czechia', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Czech cuisine (Bramborák potato pancakes)', accentColor: '#4C764F', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD49', nameEn: 'Global Table — Bhutan', nameTh: 'Global Table — Bhutan', shortName: 'Bhutan', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Bhutanese cuisine (chili cheese stew with rice)', accentColor: '#F5C63C', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD50', nameEn: 'Global Table — India', nameTh: 'Global Table — India', shortName: 'India', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Indian cuisine (mango lassi, traditional drinks)', accentColor: '#FF919C', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD51', nameEn: 'French Food Fair', nameTh: 'French Food Fair', shortName: 'French Food Fair', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'French cuisine (Poulet Basquaise, Crêpes)', accentColor: '#F0A445', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD52', nameEn: 'Global Table — Myanmar: Glass Noodle Soup', nameTh: 'Global Table — Myanmar: Glass Noodle Soup', shortName: 'Glass Noodle Soup', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Burmese cuisine (glass noodle soup)', accentColor: '#45CFC0', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD53', nameEn: 'Global Table — Myanmar: Mandalay Noodle Salad', nameTh: 'Global Table — Myanmar: Mandalay Noodle Salad', shortName: 'Mandalay Salad', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Burmese rice noodle salad from the Mandalay region', accentColor: '#E08761', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD54', nameEn: 'Global Table — Myanmar: Assorted Noodle Salad', nameTh: 'Global Table — Myanmar: Assorted Noodle Salad', shortName: 'Noodle Salad', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Burmese assorted noodle salad street food', accentColor: '#2F5D3E', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD55', nameEn: 'Global Table — Myanmar: Turmeric Sticky Rice', nameTh: 'Global Table — Myanmar: Turmeric Sticky Rice', shortName: 'Sticky Rice', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Burmese yellow sticky rice with turmeric', accentColor: '#EF5F5F', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD56', nameEn: 'Global Table — Myanmar: Pyay Rice Salad', nameTh: 'Global Table — Myanmar: Pyay Rice Salad', shortName: 'Pyay Rice Salad', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Pyay-style rice salad from the Bago region', accentColor: '#0FAFD0', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD57', nameEn: 'Global Table — Myanmar: Shan Table', nameTh: 'Global Table — Myanmar: Shan Table', shortName: 'Shan Table', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Shan tea leaf salad and Shan-Bamar stuffed tomatoes', accentColor: '#4C764F', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD58', nameEn: 'Global Table — Myanmar: Tea Shop Fritters', nameTh: 'Global Table — Myanmar: Tea Shop Fritters', shortName: 'Tea Shop Fritters', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Burmese vegetable fritters from tea shop culture', accentColor: '#F5C63C', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD59', nameEn: 'Global Table — Myanmar: Desserts', nameTh: 'Global Table — Myanmar: Desserts', shortName: 'Myanmar Desserts', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Burmese desserts (sago soup, steamed banana)', accentColor: '#FF919C', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD60', nameEn: 'Global Table — Myanmar: Rice Drop Dessert', nameTh: 'Global Table — Myanmar: Rice Drop Dessert', shortName: 'Rice Drop Dessert', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Burmese rice drop dessert with coconut milk', accentColor: '#F0A445', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD61', nameEn: 'Global Table — Myanmar: Shan Rice Cake', nameTh: 'Global Table — Myanmar: Shan Rice Cake', shortName: 'Shan Rice Cake', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Shan steamed rice cake with garlic and chili oil', accentColor: '#45CFC0', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD62', nameEn: 'Global Table — Karen Curry', nameTh: 'Global Table — Karen Curry', shortName: 'Karen Curry', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Karen traditional curry with local herbs', accentColor: '#E08761', zone: 'entrance', isPrizeDesk: false },
  { id: 'FD63', nameEn: 'Global Table — Myanmar: Rakhine Table', nameTh: 'Global Table — Myanmar: Rakhine Table', shortName: 'Rakhine Table', hostUnit: 'GRD', category: 'food', location: 'International Food & Culture', descriptionEn: 'Rakhine soup and anchovy salad from coastal Myanmar', accentColor: '#2F5D3E', zone: 'entrance', isPrizeDesk: false },
  { id: 'OPEN1', nameEn: 'Green Table', nameTh: 'Green Table', shortName: 'Green Table', hostUnit: 'M-Store x Zero Waste (Grace) 1', category: 'market', location: 'Open Space · Market', descriptionEn: 'Natural plant fiber plates and bowls from Gracz (100% sugarcane pulp)', accentColor: '#EF5F5F', zone: 'entrance', isPrizeDesk: false },
  { id: 'OPEN2', nameEn: 'M-Store', nameTh: 'M-Store', shortName: 'M-Store', hostUnit: 'M-Store x Zero Waste (Grace) 2', category: 'market', location: 'Open Space · Market', descriptionEn: 'MFU university products', accentColor: '#0FAFD0', zone: 'entrance', isPrizeDesk: false },
  { id: 'OPEN3', nameEn: 'ปะ ดิ มา กำ', nameTh: 'ปะ ดิ มา กำ', shortName: 'ปะ ดิ มา กำ', hostUnit: 'GRD', category: 'youth', location: 'Open Space · Youth', descriptionEn: 'Student workshops on entrepreneurship and creative crafts', accentColor: '#4C764F', zone: 'entrance', isPrizeDesk: false },
  { id: 'OPEN4', nameEn: 'Daisy Belle X Nadtasin MFU', nameTh: 'Daisy Belle X Nadtasin MFU', shortName: 'Daisy Belle', hostUnit: 'GRD', category: 'youth', location: 'Open Space · Youth', descriptionEn: 'Bag-making supplies, instruction, and hair accessories', accentColor: '#F5C63C', zone: 'entrance', isPrizeDesk: false },
  { id: 'OPEN5', nameEn: '¡LOTERÍA! — A Taste of Mexico', nameTh: '¡LOTERÍA! — A Taste of Mexico', shortName: '¡LOTERÍA!', hostUnit: 'GRD', category: 'youth', location: 'Open Space · Youth', descriptionEn: 'Traditional Mexican Lotería game with cultural education', accentColor: '#FF919C', zone: 'entrance', isPrizeDesk: false },
  { id: 'OPEN6', nameEn: 'Crochet and Embroidery', nameTh: 'Crochet and Embroidery', shortName: 'Crochet', hostUnit: 'GRD', category: 'youth', location: 'Open Space · Youth', descriptionEn: 'Student crochet and embroidery projects and sales', accentColor: '#F0A445', zone: 'entrance', isPrizeDesk: false },
  { id: 'OPEN7', nameEn: 'Model United Nations', nameTh: 'Model United Nations', shortName: 'MUN', hostUnit: 'GRD', category: 'youth', location: 'Open Space · Youth', descriptionEn: 'MUN student activities and presentations', accentColor: '#45CFC0', zone: 'entrance', isPrizeDesk: false },
  { id: 'OPEN8', nameEn: 'MFU Human Rights Club', nameTh: 'MFU Human Rights Club', shortName: 'Human Rights Club', hostUnit: 'GRD', category: 'youth', location: 'Open Space · Youth', descriptionEn: 'MFU Human Rights Club activities', accentColor: '#E08761', zone: 'entrance', isPrizeDesk: false },
  { id: 'OPEN9', nameEn: 'Maxim', nameTh: 'Maxim', shortName: 'Maxim', hostUnit: 'GRD', category: 'youth', location: 'Open Space · Youth', descriptionEn: 'Maxim student organization activities', accentColor: '#2F5D3E', zone: 'entrance', isPrizeDesk: false },
  { id: 'OPEN10', nameEn: 'International Student Club I', nameTh: 'International Student Club I', shortName: 'ISC I', hostUnit: 'GRD', category: 'youth', location: 'Open Space · Youth', descriptionEn: 'International Student Club activities', accentColor: '#EF5F5F', zone: 'entrance', isPrizeDesk: false },
  { id: 'OPEN11', nameEn: 'International Student Club II', nameTh: 'International Student Club II', shortName: 'ISC II', hostUnit: 'GRD', category: 'youth', location: 'Open Space · Youth', descriptionEn: 'International Student Club activities', accentColor: '#0FAFD0', zone: 'entrance', isPrizeDesk: false },
  { id: 'OPEN12', nameEn: 'International Student Club III', nameTh: 'International Student Club III', shortName: 'ISC III', hostUnit: 'GRD', category: 'youth', location: 'Open Space · Youth', descriptionEn: 'International Student Club activities', accentColor: '#4C764F', zone: 'entrance', isPrizeDesk: false },
  { id: 'OPEN13', nameEn: 'First Aid Service', nameTh: 'First Aid Service', shortName: 'First Aid', hostUnit: 'MFU Medical Center Hospital', category: 'wellness', location: 'Wellness', descriptionEn: 'Medical first aid service station', accentColor: '#F5C63C', zone: 'entrance', isPrizeDesk: false },
]

/** Every booth is worth this before the quiet/busy adjustment moves it. */
export const BOOTH_BASE_POINTS = 10
